import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { calculateNatalChart } from '../chart/natal-engine.mjs';
import { calculateDaewoon } from '../chart/daewoon-engine.mjs';

const html = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const adminAreaSource = fs.readFileSync(new URL('../data/admin-areas.js', import.meta.url), 'utf8');
const apacheSslConfig = fs.readFileSync(new URL('../deploy/apache/saju.blog-le-ssl.conf', import.meta.url), 'utf8');
const deployUpdater = fs.readFileSync(new URL('../deploy/bin/update-saju-app.sh', import.meta.url), 'utf8');
const serviceUnit = fs.readFileSync(new URL('../deploy/systemd/saju-app.service', import.meta.url), 'utf8');
const engineStart = html.indexOf('const STEMS');
const engineEnd = html.indexOf('function getFact');
assert.ok(engineStart >= 0, 'engine constants are present');
assert.ok(engineEnd > engineStart, 'engine boundary is present');

const engineSource = html.slice(engineStart, engineEnd);
const catalogSandbox = {};
vm.runInNewContext(adminAreaSource, catalogSandbox);
vm.runInNewContext(`${engineSource};
  globalThis.birthPlaces = BIRTH_PLACE_VALUES;
  globalThis.munhyeon = resolveBirthPlace('문현동');
  globalThis.ambiguousPlace = resolveBirthPlace('사직동');
  globalThis.munhyeonSuggestions = findBirthPlaceSuggestions('문현동');
  globalThis.samsungSuggestions = findBirthPlaceSuggestions('삼성동');
  const originalLocaleCompare = String.prototype.localeCompare;
  globalThis.localeCompareCalls = 0;
  String.prototype.localeCompare = function (...args) { globalThis.localeCompareCalls += 1; return originalLocaleCompare.apply(this, args); };
  globalThis.haeundaeSuggestions = findBirthPlaceSuggestions('해운대');
  String.prototype.localeCompare = originalLocaleCompare;
  globalThis.tenGodMap = STEMS.map((stem) => [stem, tenGodFor('戊', stem)]);
`, catalogSandbox);
const birthPlaces = Array.from(catalogSandbox.birthPlaces);
assert.equal(birthPlaces.length, 21836, 'birthplace catalog combines current administrative and legal localities from the official snapshot');
assert.equal(new Set(birthPlaces).size, 21836, 'birthplace catalog has no duplicate display names');
assert.ok(birthPlaces.includes('서울특별시 강남구 역삼1동'));
assert.ok(birthPlaces.includes('대구광역시 군위군 군위읍'));
assert.ok(birthPlaces.includes('세종특별자치시 집현동'));
assert.ok(birthPlaces.includes('부산광역시 남구 문현동'));
assert.equal(catalogSandbox.munhyeon.status, 'matched');
assert.equal(catalogSandbox.munhyeon.name, '부산광역시 남구 문현동');
assert.equal(catalogSandbox.munhyeon.code, '2629010900');
assert.equal(catalogSandbox.ambiguousPlace.status, 'ambiguous');
assert.equal(catalogSandbox.munhyeonSuggestions[0].name, '부산광역시 남구 문현동');
assert.equal(catalogSandbox.samsungSuggestions.length, 5);
assert.ok(catalogSandbox.samsungSuggestions.some(({ name }) => name === '서울특별시 강남구 삼성동'));
assert.equal(catalogSandbox.haeundaeSuggestions.length, 20);
assert.ok(catalogSandbox.haeundaeSuggestions.some(({ name }) => name.includes('해운대')));
assert.equal(catalogSandbox.localeCompareCalls, 0, 'birthplace filtering does not sort the full catalog while the user types');
assert.match(adminAreaSource, /Effective date: 2026-07-20/);
assert.match(adminAreaSource, /KIKcd_H and KIKcd_B/);
assert.deepEqual(JSON.parse(JSON.stringify(catalogSandbox.tenGodMap)), [['甲', '편관'], ['乙', '정관'], ['丙', '편인'], ['丁', '정인'], ['戊', '비견'], ['己', '겁재'], ['庚', '식신'], ['辛', '상관'], ['壬', '편재'], ['癸', '정재']], 'ten-god relation covers all five element relations and both polarities');
const evaluate = (input) => {
  const sandbox = { calculateNatalChart, calculateDaewoon };
  vm.runInNewContext(`${engineSource}; globalThis.result = calculateChart(${JSON.stringify(input)});`, sandbox);
  return sandbox.result;
};

const golden = evaluate({ date: '1990-10-10', time: '14:30', unknownTime: false, place: '서울', calendar: 'solar', sex: 'unset', samePerson: true });
assert.deepEqual(Array.from(golden.pillars, (pillar) => pillar.text), ['庚午', '丙戌', '戊申', '己未']);
assert.equal(golden.policy.id, 'KR-CIVIL-1.0');
assert.equal(golden.policy.version, '1.0.0');
assert.equal(golden.policy.engine, 'gyeol-natal-core');
assert.equal(golden.policy.engineVersion, '1.0.0');
assert.ok(golden.facts.every((fact) => fact.id && fact.value), 'facts have stable identifiers and values');
assert.equal(golden.reading.length, 8, 'single reading includes eight evidence-grounded chapters');
assert.ok(golden.reading.every((item) => item.detail && item.practice && item.questions?.length >= 2), 'single reading includes detail, practice, and prompts');
assert.match(golden.reading[0].text, /토가 4개/);
assert.match(golden.reading[0].detail, /^토는 /);
assert.match(golden.reading[1].text, /己는 겁재/);
assert.equal(golden.pillars[0].tenGod, '식신');
assert.deepEqual(Array.from(golden.pillars[2].hiddenStems), ['庚', '壬', '戊']);
assert.ok(golden.facts.some((fact) => fact.id === 'ten-god.visible'));
assert.ok(golden.facts.some((fact) => fact.id === 'hidden-stems'));
const daewoonFact = golden.facts.find((fact) => fact.id === 'cycles.daewoon');
assert.ok(daewoonFact, 'daewoon fact exists');
assert.match(daewoonFact.value, /^.{2} \(\d+세~\)$/, 'daewoon fact reports a pillar and start age');
assert.match(daewoonFact.detail, /KR-DAEWOON-1\.0/);
assert.ok(golden.daewoon, 'daewoon object is attached to chart result');
assert.equal(golden.daewoon.cycles.length, 8);
assert.equal(golden.daewoon.cycles[0].pillar, `${golden.pillars[1].text}`);

const unknownTime = evaluate({ date: '1990-10-10', time: '12:00', unknownTime: true, place: '서울', calendar: 'solar', sex: 'unset', samePerson: true });
assert.equal(unknownTime.pillars[3].text, '미상');
assert.ok(unknownTime.warnings.some((warning) => warning.fact === 'input.unknown-time'));

const boundary = evaluate({ date: '2024-02-04', time: '17:00', unknownTime: false, place: '서울', calendar: 'solar', sex: 'unset', samePerson: true });
assert.ok(boundary.warnings.some((warning) => warning.fact === 'boundary.solar-term'));
assert.ok(boundary.facts.some((fact) => fact.id === 'boundary.solar-term' && /癸卯·乙丑 → 甲辰·丙寅/.test(fact.value)));
assert.match(html, /function warningMarkup\(warnings\)/, 'boundary warnings use a shared evidence renderer');
assert.match(html, /aria-expanded="\$\{isActive\}"[\s\S]*?isActive \? `<div class="fact-detail">/, 'boundary evidence expands into a visible detail');
assert.match(apacheSslConfig, /^\s*ProxyPass \/ http:\/\/127\.0\.0\.1:4174\/$/m, 'Apache sends all HTTPS assets through the Node public allowlist');
assert.match(apacheSslConfig, /^\s*ProxyPassReverse \/ http:\/\/127\.0\.0\.1:4174\/$/m, 'Apache preserves reverse-proxy responses for all HTTPS assets');
assert.match(deployUpdater, /install -m 644 deploy\/apache\/saju\.blog-le-ssl\.conf \/etc\/apache2\/sites-available\/saju\.blog-le-ssl\.conf/, 'the release updater installs the reviewed HTTPS proxy boundary');
assert.match(deployUpdater, /apache2ctl configtest[\s\S]*systemctl reload apache2/, 'the release updater validates Apache before reloading it');
assert.match(deployUpdater, /install -m 755 deploy\/bin\/update-saju-app\.sh \/usr\/local\/sbin\/saju-app-update/, 'the deployed updater refreshes itself after a healthy release');
assert.match(deployUpdater, /RUNTIME_DIR="\$STATE_DIR\/runtime"/, 'SQLite runtime state has a dedicated service-writable directory');
assert.match(deployUpdater, /mv "\$STATE_DIR\/saju\.sqlite" "\$RUNTIME_DIR\/saju\.sqlite"/, 'the updater preserves an existing production SQLite database during migration');
assert.match(serviceUnit, /Environment=SAJU_DB_PATH=\/var\/lib\/saju-app\/runtime\/saju\.sqlite/, 'the service reads the database from the runtime boundary');
assert.match(serviceUnit, /ReadWritePaths=\/var\/lib\/saju-app\/runtime/, 'systemd grants writes only to the runtime boundary');

const couple = (() => {
  const sandbox = { calculateNatalChart, calculateDaewoon };
  vm.runInNewContext(`${engineSource}; globalThis.result = calculateCoupleChart(${JSON.stringify({ date: '1990-10-10', time: '14:30', unknownTime: false, place: '서울', calendar: 'solar' })}, ${JSON.stringify({ date: '1992-02-14', time: '09:00', unknownTime: false, place: '서울', calendar: 'solar' })}, 'dating');`, sandbox);
  return sandbox.result;
})();
assert.equal(couple.mode, 'couple');
assert.equal(couple.self.pillars.length, 4);
assert.equal(couple.partner.pillars.length, 4);
assert.ok(couple.facts.some((fact) => fact.id === 'relationship.shared.element'));
assert.equal(couple.reading.length, 7, 'couple reading includes seven evidence-grounded chapters');
assert.ok(couple.reading.every((item) => item.detail && item.practice && item.questions?.length >= 2), 'couple reading includes detail, practice, and prompts');
assert.match(couple.reading[3].detail, /토와 관련된 행동/);
assert.ok(couple.facts.some((fact) => fact.id === 'self.ten-god.visible'));
assert.ok(couple.facts.some((fact) => fact.id === 'partner.hidden-stems'));

assert.match(html, /import \{ createAnnualStorage \} from '\.\/annual\/storage\.mjs'/);
assert.match(html, /purpose-receipt-bound/);
assert.match(html, /serviceWorker\.register/);
assert.match(html, /aria-live/);
assert.match(html, /커플 사주/);
assert.match(html, /입력 권한을 확인한 상대방의 출생정보/);
assert.match(html, /두 사람의 사주풀이 시작하기/);
assert.match(html, /couple-input-pair/);
assert.match(html, /consent-list/);
assert.match(html, /partnerForm\.authorityVerified = state\.mode === 'couple'/);
assert.doesNotMatch(html, /form\.get\('partnerAuthority'\)/);
assert.doesNotMatch(html, /상대방의 동의를 받고 입력합니다/);
assert.doesNotMatch(html, /id="partner-authority"/);
assert.doesNotMatch(html, /<script src="data\/admin-areas\.js/);
assert.match(html, /function loadBirthPlaceData\(\)/);
assert.match(html, /birthPlaceStatus: 'idle'/);
assert.match(html, /<select id="\$\{prefix\}-place-select">/);
assert.match(html, /출생한 동·읍·면·리/);
assert.match(html, /syncBirthPlaceDraft/);
assert.match(html, /commitBirthPlace/);
assert.match(html, /place-match-panel/);
assert.match(html, /selectBirthPlace/);
assert.match(html, /검색 결과에서 출생지를 골라 주세요/);
assert.match(html, /검색 결과가 많아 먼저 20곳을 보여드려요/);
assert.match(html, /placeResolution\.status === 'ambiguous'/);
assert.match(html, /reading-report/);
assert.match(html, /십신의 겉흐름/);
assert.match(html, /지장간의 안쪽 흐름/);
assert.match(html, /reading-practice/);
assert.match(html, /한눈에 보기/);
assert.match(html, /쉽게 풀어보면/);
assert.match(html, /오늘 해볼 일/);
assert.match(html, /생각해볼 질문/);
assert.match(html, /data-action="text-size"/);
assert.match(html, /reading-size-large/);
assert.match(html, /function methodView\(\)/);
assert.match(html, /function dataView\(\)/);
assert.match(html, /state\.screen = 'method'/);
assert.match(html, /state\.screen = 'data'/);
assert.match(html, /moveToStage\('input-title'/);
assert.match(html, /state\.screen === 'result'\) moveToStage\('result-title'\)/);
assert.match(html, /if \(!state\.serviceConsent\)/);
assert.doesNotMatch(html, /!state\.serviceConsent \|\| !state\.training/);
assert.match(html, /제품 개선을 위한 학습 사용 \(선택\)/);
assert.match(html, /\.mode-card small \{[^}]*font-size: 15px/s);
assert.match(html, /\.brand-copy small \{[^}]*font-size: 13px/s);
assert.match(html, /\.mobile-nav button \{[^}]*font-size: 15px/s);
assert.match(html, /Noto\+Sans\+KR:wght@400&family=Noto\+Serif\+KR:wght@600/);
assert.doesNotMatch(html, /wght@400;500;600;700;800/);
assert.match(html, /\.info-card \{[^}]*--ink-950: #302c3a[^}]*color: var\(--ink-950\)/s);
assert.doesNotMatch(html, /<h3>저장 상태<\/h3>/);
assert.doesNotMatch(html, /<dt>계산 엔진<\/dt>/);
assert.doesNotMatch(html, /function polishCopy\(/);
assert.doesNotMatch(html, /Couple input|Birth input|Evidence-grounded|Fixed chart facts/);
assert.doesNotMatch(html, /copy\.replaceChildren|button\.disabled = false/);
assert.match(html, /data-value="lunar" aria-pressed="\$\{form\.calendar === 'lunar'\}"/);
assert.match(html, /calendar\/convert/);
assert.match(html, /lunarYear/);
assert.match(html, /result\.durable === false \? 'outbox' : 'saved'/);
assert.match(html, /cg-canary/);
assert.match(html, /copyright\.html/);
assert.match(fs.readFileSync(new URL('../robots.txt', import.meta.url), 'utf8'), /GPTBot[\s\S]*Disallow: \//);
assert.match(fs.readFileSync(new URL('../ai.txt', import.meta.url), 'utf8'), /ClaudeBot[\s\S]*Disallow: \//);
assert.match(fs.readFileSync(new URL('../service-worker.js', import.meta.url), 'utf8'), /saju-app-shell-v11/);
assert.match(fs.readFileSync(new URL('../service-worker.js', import.meta.url), 'utf8'), /annual\/client\.mjs/);
assert.match(fs.readFileSync(new URL('../service-worker.js', import.meta.url), 'utf8'), /annual\/storage\.mjs/);
assert.match(fs.readFileSync(new URL('../service-worker.js', import.meta.url), 'utf8'), /chart\/natal-engine\.mjs/);
assert.match(fs.readFileSync(new URL('../service-worker.js', import.meta.url), 'utf8'), /chart\/natal-ephemeris-data\.mjs/);
assert.match(fs.readFileSync(new URL('../service-worker.js', import.meta.url), 'utf8'), /chart\/daewoon-engine\.mjs/);
assert.match(html, /requestAnnualReading/);
assert.match(html, /annualSubmissionFields/);
assert.match(html, /name="targetYear"/);
assert.match(html, /name="targetYear" type="number" min="2024" max="2026"/);
assert.doesNotMatch(html, /연운은 1900~2099년/);
assert.match(html, /연운 지장간 활성화·가중치/);
assert.match(html, /data-action="annual-prev"|renderAnnualReading/);
assert.match(html, /\.annual-card:focus[^\{]*\{[^}]*outline: 3px solid var\(--gold-500\)[^}]*box-shadow: 0 0 0 3px var\(--gold-500\)/s);
assert.match(html, /명식과 연운 카드 만들기/);
assert.match(html, /\.result-main > :not\(\.annual-reading\)/, 'print hides natal input and leaves only the privacy-safe annual document');
assert.doesNotMatch(fs.readFileSync(new URL('../service-worker.js', import.meta.url), 'utf8'), /data\/admin-areas\.js/);
assert.match(fs.readFileSync(new URL('../service-worker.js', import.meta.url), 'utf8'), /skipWaiting/);
assert.match(fs.readFileSync(new URL('../service-worker.js', import.meta.url), 'utf8'), /caches\.match\('\.\/index\.html'\)/);

const assertionCount = (fs.readFileSync(new URL(import.meta.url), 'utf8').match(/\bassert\./g) || []).length;
console.log(`saju smoke: ${assertionCount} assertions passed`);
