// server/storage/seeds/month-im-gye.mjs
// 월지 패턴 시드: 임수·계수 일간 × 12월지 = 24개 패턴
// 명리학적 근거: 자평명리의 일간·월지 오행 상호작용. 한자 최소화, 일상어 paraphrasing.
// 작성일: 2026-08-06

export const MONTH_IM_GYE = { patterns: [

// ============================================================
// 임수(壬) 일간 — 바다·큰 강 (양수)
// 흐르고 퍼지고 자유롭게 움직이는 힘, 포용력, 지혜.
// 정착 어려움·흩어짐 주의.
// ============================================================

// ── 임 × 인 (봄, 수생목) ──────────────────────────
{
  month_pattern_id: '임_인', day_master: '임', month_branch: '인',
  season: '봄', element_interaction: '수생목',
  label: '임수 × 인월지 — 큰 물이 봄의 새싹을 키우며 흘러가는 자리',
  modules: [
    { module_id: '임_인_mindset', month_pattern_id: '임_인', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['물이 나무를 길러 키우듯 에너지가 밖으로 흘러나가는 시기입니다 — 무언가를 키우고 기르는 일에 보람이 있습니다', '바다처럼 넓은 시야로 가능성을 보되, 한두 가지에 한정해 집중해야 흩어지지 않습니다', '시작의 계절인 만큼 심는 마음으로 움직이세요 — 수확은 아직 아닙니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_인_health', month_pattern_id: '임_인', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['물이 나무에게 쓰이면서 에너지가 소모되기 쉽습니다 — 무리하지 말고 충분히 쉬세요', '간·피로감이 올 수 있으니 봄나물과 따뜻한 차로 몸을 보살피세요', '물을 자주 마시되 한 번에 많이 마시지 말고 조금씩 자주 드세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_인_career', month_pattern_id: '임_인', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['키우고 기르는 일 — 교육, 육성, 프로젝트 매니징에 에너지가 잘 맞습니다', '넓은 지식과 경험을 한 방향으로 흘려보내 결과물로 키우는 데 유리합니다', '여러 일에 손을 대면 물이 여러 갈래로 갈라지듯 힘이 분산되니, 우선순위를 정하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_인_romance', month_pattern_id: '임_인', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['상대를 키워주고 돕는 관계가 자연스럽게 열립니다', '너무 베풀기만 하면 지치니, 받는 것도 허용하세요', '활기로운 봄 공기 속에서 새로운 만남에 유리하되 첫인상에 휩쓸리지 마세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_인_wealth', month_pattern_id: '임_인', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈이 밖으로 흘러나가기 쉬운 시기입니다 — 쓸 곳은 많으니 예산을 정하세요', '키우는 일에 투자하면 장기적으로 돌아옵니다 — 교육, 씨앗 프로젝트에 쓴 돈은 나중에 자랍니다', '당장 수확을 기대하기보다 씨앗값이라 생각하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_인_relationships', month_pattern_id: '임_인', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['포용력이 넓어지는 시기라 다양한 사람과 어울리기 좋습니다', '모두에게 베풀려다 정작 소중한 사람을 놓칠 수 있으니 우선순위를 정하세요', '후배나 제자를 돕는 자리에서 좋은 인연이 맺어집니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_인_growth', month_pattern_id: '임_인', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['새로운 분야의 씨앗을 심기 좋은 시기입니다 — 호기심을 따라 배우세요', '배운 것을 남에게 가르치며 자기 것으로 만드세요', '한 번에 깊이 파려 하지 말고 넓게 심은 뒤 좁혀 가세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_인_must_do', month_pattern_id: '임_인', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['한두 가지를 정해 키우고 끝까지 가세요 — 흩어지는 것이 임수의 가장 큰 위험입니다', '에너지 소모가 크니 휴식과 충전을 일정에 넣으세요'], closing: '물이 나무를 키우듯, 흘러가는 힘을 한 곳에 머물게 해 결실로 이끄는 것이 이 자리의 숙제입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 임 × 묘 (봄, 수생목) ──────────────────────────
{
  month_pattern_id: '임_묘', day_master: '임', month_branch: '묘',
  season: '봄', element_interaction: '수생목',
  label: '임수 × 묘월지 — 큰 물이 무성한 초목 속으로 스며드는 자리',
  modules: [
    { module_id: '임_묘_mindset', month_pattern_id: '임_묘', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['나무가 무성하게 자라 물을 빨아들이듯, 무언가에 깊이 빠져들기 쉬운 시기입니다', '감성과 표현 욕구가 강해집니다 — 창작, 예술, 기획에 에너지가 잘 맞습니다', '정서적으로 예민해지니 감정의 흐름을 관찰하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_묘_health', month_pattern_id: '임_묘', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['에너지가 빨려나가듯 소모되니 과로를 경계하세요', '간·스트레스성 피로가 오기 쉽습니다 — 충분한 수면이 우선입니다', '산책이나 가벼운 스트레칭으로 기운을 순환시키세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_묘_career', month_pattern_id: '임_묘', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['창작, 기획, 콘텐츠, 디자인 등 표현하는 일에 강합니다', '아이디어가 풍부하지만 끝맺음이 약해질 수 있으니 마감 기한을 명확히 하세요', '혼자서 감당하기보다 팀원에게 일을 나누세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_묘_romance', month_pattern_id: '임_묘', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['매력이 돋보이는 시기입니다 — 감성적으로 끌리는 만남이 열립니다', '너무 깊이 빠지면 객관성을 잃으니 한 발 떨어져 보는 연습이 필요합니다', '기존 인연이 있다면 감정 표현을 풍부하게 하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_묘_wealth', month_pattern_id: '임_묘', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈이 감정적 소비로 흘러나가기 쉽습니다 — 충동 구매를 경계하세요', '창작이나 표현에 투자하면 결실이 있으되 시간이 걸립니다', '감정이 출렁일 때는 지출을 미루세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_묘_relationships', month_pattern_id: '임_묘', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['사람을 끌어당기는 힘이 강하지만, 관계의 깊이보다 넓이에 휩쓸리지 마세요', '감성이 풍부해져 공감 능력이 높아집니다', '인연의 유혹이 많은 시기이니 정도를 지키세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_묘_growth', month_pattern_id: '임_묘', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['예술, 문학, 미적 감각을 기르기 좋은 시기입니다', '감정을 기록하는 습관 — 일기, 글쓰기가 내면을 정돈합니다', '배운 것을 창작물로 표현하면 앎이 깊어집니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_묘_must_do', month_pattern_id: '임_묘', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['감정에 휩쓸리지 않고 객관적 중심을 잡으세요', '시작한 것을 끝까지 마무리하는 훈련이 필요합니다'], closing: '무성한 초목에 물이 스며들듯 에너지가 밖으로 쏠리는 자리입니다 — 빠져드는 힘을 의식하되 흘러가지 않게 닻을 내리세요.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 임 × 진 (봄, 토극수-완화) ───────────────────
{
  month_pattern_id: '임_진', day_master: '임', month_branch: '진',
  season: '봄', element_interaction: '토극수_완화',
  label: '임수 × 진월지 — 축축한 봄흙이 큰 물을 품어 저장하는 자리',
  modules: [
    { module_id: '임_진_mindset', month_pattern_id: '임_진', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['흩어지려는 물이 축축한 흙에 닿아 머무는 시기입니다 — 정착과 저장이 자리를 잡습니다', '자유를 잃은 것 같은 답답함이 올 수 있으나 그것이 결실의 조건입니다', '모으고 쌓는 마음으로 움직이세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_진_health', month_pattern_id: '임_진', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['습기와 차수(비·신장) 건강에 유의하세요', '물이 흙에 갇혀 답답함이 스트레스가 될 수 있습니다 — 가벼운 운동으로 기운을 푸세요', '위장이 예민해질 수 있으니 과식을 피하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_진_career', month_pattern_id: '임_진', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['저장과 정착의 기운이 강하니 문서, 계약, 자산 관리에 유리합니다', '그동안 흩어져 있던 일을 모아 하나로 묶는 데 힘을 쓰세요', '안정을 추구하는 자리에서 인정을 받을 수 있습니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_진_romance', month_pattern_id: '임_진', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['관계가 안정적으로 자리 잡는 시기입니다 — 진지한 인연이 깊어집니다', '답답함을 자유의 부재로 해석하면 관계가 흔들립니다', '함께 무언가를 모아가는 관계가 좋습니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_진_wealth', month_pattern_id: '임_진', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['저축과 자산 형성에 가장 유리한 자리입니다 — 모으는 해입니다', '큰 지출은 계획적으로 결정하면 자산이 됩니다', '흘려 보내는 돈을 줄이고 저축 비율을 높이세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_진_relationships', month_pattern_id: '임_진', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['신뢰할 수 있는 사람과 깊은 관계를 맺기 좋습니다', '넓은 인맥보다 좁고 단단한 관계가 도움이 됩니다', '가족과 함께 시간을 보내며 뿌리를 내리세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_진_growth', month_pattern_id: '임_진', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['배운 것을 체계적으로 정리하고 저장하는 데 유리합니다', '한 가지 주제를 깊이 파고드는 몰입의 시간을 만드세요', '지식을 자산으로 묶어 내는 — 강의, 글, 자격증 — 작업이 잘 풀립니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_진_must_do', month_pattern_id: '임_진', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['흩어진 에너지를 한 곳에 모아 저장하세요', '정착의 답답함을 견디고 뿌리를 내리세요'], closing: '축축한 흙이 물을 품듯, 흐르던 힘이 머물러 결실의 토대가 되는 자리입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 임 × 사 (여름, 수극화) ───────────────────────
{
  month_pattern_id: '임_사', day_master: '임', month_branch: '사',
  season: '여름', element_interaction: '수극화',
  label: '임수 × 사월지 — 큰 물이 초여름 불과 마주하는 긴장의 자리',
  modules: [
    { module_id: '임_사_mindset', month_pattern_id: '임_사', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['물과 불이 만나 증기가 피어오르듯 에너지가 역동적으로 움직입니다', '감정과 열정이 출렁이는 시기이니 한 박자 늦추어 조절하는 것이 중요합니다', '긴장 자체가 나쁜 것이 아닙니다 — 그 긴장을 동력으로 쓰세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_사_health', month_pattern_id: '임_사', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['물·불의 긴장으로 피로와 감정 기복이 올 수 있습니다', '심장·혈액순환을 살피고 수분을 충분히 보충하세요', '밤늦게까지 흥분된 상태로 지내면 수면에 영향이 갑니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_사_career', month_pattern_id: '임_사', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['통찰을 제안으로 내놓으면 기회로 이어지는 시기입니다', '기획, 발표, 협상 등에서 물의 차가움과 불의 열정을 번갈아 쓰세요', '감정적으로 나가면 갈등이 생기니 말의 온도를 조절하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_사_romance', month_pattern_id: '임_사', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['강렬한 끌림이 있는 시기이되, 열정이 식은 뒤를 미리 생각하세요', '지적인 대화가 오가는 자리에서 인연이 열립니다', '감정의 기복이 관계에 영향을 주니 한 박자 쉬어 가세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_사_wealth', month_pattern_id: '임_사', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['기회성 수입이 열릴 수 있으되 들쑥날쑥합니다', '감정적으로 큰돈을 쓰는 순간을 피하세요', '들어올 때 모아 두어야 흐름이 안정됩니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_사_relationships', month_pattern_id: '임_사', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['말이 오가는 자리에서 인연이 피어나되, 날카로운 말은 상처가 됩니다', '듣는 귀를 무겁게 하세요', '감정이 출렁일 때는 결정을 미루는 것이 관계를 지킵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_사_growth', month_pattern_id: '임_사', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['실전에 가까운 경험이 성장을 앞당깁니다 — 발표, 토론, 현장', '감정 관리가 올해의 가장 큰 배움입니다', '한 박자 쉬는 습관이 판단의 질을 높입니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_사_must_do', month_pattern_id: '임_사', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['감정과 에너지의 출렁임을 한 박자 늦춰 조절하세요', '물·불의 긴장을 갈등이 아닌 동력으로 쓰세요'], closing: '큰 물이 불을 만나 증기가 되듯, 긴장을 창조적 에너지로 바꾸는 것이 이 자리의 숙제입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 임 × 오 (여름, 수극화) ───────────────────────
{
  month_pattern_id: '임_오', day_master: '임', month_branch: '오',
  season: '여름', element_interaction: '수극화',
  label: '임수 × 오월지 — 큰 물이 한여름 태양 아래서 가장 치열하게 조우하는 자리',
  modules: [
    { module_id: '임_오_mindset', month_pattern_id: '임_오', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['한여름의 가장 뜨거운 불 앞에 선 큰 물입니다 — 긴장이 가장 높은 시기입니다', '물이 증발하듯 에너지가 빠르게 소모되니 과신을 경계하세요', '열기를 식히되 완전히 물러서지는 마세요 — 적당한 거리가 핵심입니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_오_health', month_pattern_id: '임_오', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['더위로 체력이 크게 소모됩니다 — 수분 보충과 휴식이 최우선입니다', '심장·혈압·눈 건강에 유의하세요', '한낮 활동을 줄이고 서늘한 환경에서 쉬는 시간을 만드세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_오_career', month_pattern_id: '임_오', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['치열한 환경에서 실력이 드러나는 시기입니다 — 결과로 증명하세요', '물·불의 정면 대결이 되는 자리라 정면 충돌보다 우회가 유리합니다', '열정과 냉정을 번갈아 쓰는 전략이 효과적입니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_오_romance', month_pattern_id: '임_오', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['열정이 강렬한 시기이되, 식은 뒤의 관계를 염두에 두세요', '강하게 다가가면 부담이 되니 적당한 거리가 매력입니다', '감정의 기복이 크니 흥분 상태의 결정을 피하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_오_wealth', month_pattern_id: '임_오', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['재물의 흐름이 빠르고 불안정합니다 — 들어오면 즉시 모으세요', '충동적 소비와 투기가 가장 위험한 시기입니다', '현금 흐름을 쥐고 큰 지출은 가을로 미루세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_오_relationships', month_pattern_id: '임_오', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['감정이 격해지기 쉬우니 말과 행동을 한 박자 늦추세요', '실수한 말은 되돌리기 어려운 시기입니다', '서늘한 공간에서 차를 나누는 등 온도를 낮추는 만남이 좋습니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_오_growth', month_pattern_id: '임_오', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['가장 치열한 환경에서 배우는 것이 깊이를 만듭니다', '감정 관리와 자기 절제가 핵심 배움입니다', '혼자만의 정리 시간을 의식적으로 만드세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_오_must_do', month_pattern_id: '임_오', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['에너지 소진을 막고 체력 관리를 최우선으로 하세요', '감정이 격할 때 말과 결정을 미루세요'], closing: '한여름 불 앞의 큰 물이 증발하지 않고 식어가듯, 치열한 긴장 속에서 자기를 잃지 않는 것이 이 자리의 숙제입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 임 × 미 (여름, 토극수) ───────────────────────
{
  month_pattern_id: '임_미', day_master: '임', month_branch: '미',
  season: '여름', element_interaction: '토극수',
  label: '임수 × 미월지 — 여름의 마른 흙이 큰 물의 흐름을 막는 자리',
  modules: [
    { module_id: '임_미_mindset', month_pattern_id: '임_미', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['마른 흙이 물을 막듯 흐름에 제약이 생기는 시기입니다', '답답함과 억눌림이 올 수 있으나 이것이 흐름을 조절하는 기회입니다', '막힌 것을 뚫으려 하기보다 막힌 동안 쌓으세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_미_health', month_pattern_id: '임_미', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['위장과 소화기 계통이 예민해집니다 — 더위와 습기를 함께 조심하세요', '스트레스성 위염, 설사 등이 올 수 있으니 식사를 규칙적으로', '충분한 수분 섭취와 가벼운 운동으로 기운을 순환시키세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_미_career', month_pattern_id: '임_미', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['규칙과 제약이 많은 환경에서 일하게 됩니다 — 인내가 성과의 열쇠입니다', '막힌 부분을 억지로 뚫기보다 우회와 대안을 찾으세요', '상반기의 일을 정리하고 하반기를 준비하는 데 유리합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_미_romance', month_pattern_id: '임_미', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['관계에 답답함이 생길 수 있는 시기입니다', '억눌린 감정을 표현하되 비난이 되지 않게 하세요', '서로의 공간을 존중하며 거리 조절이 필요합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_미_wealth', month_pattern_id: '임_미', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈의 흐름이 느려지고 제약이 생길 수 있습니다', '지출을 최소화하고 비상금을 확보하세요', '투자는 보수적으로, 새로운 투기는 절대 피하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_미_relationships', month_pattern_id: '임_미', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['사람 관계에서 억눌림이나 의무감이 클 수 있습니다', '맺고 끊는 것이 명확하지 않으면 에너지가 샙니다', '소수의 신뢰할 수 있는 사람과만 깊이 교류하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_미_growth', month_pattern_id: '임_미', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['제약 속에서 인내를 기르는 시기입니다 — 배움의 깊이가 늘어납니다', '막힘을 겪으며 배우는 것이 나중에 큰 자산이 됩니다', '정리와 반성의 시간을 가지세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_미_must_do', month_pattern_id: '임_미', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['답답함을 견디고 막힌 동안 내실을 다지세요', '억지로 뚫으려 하지 말고 우회와 대안을 찾으세요'], closing: '마른 흙이 물을 막듯 흐름에 제약이 오는 자리입니다 — 멈춤이 아니라 조절의 시간으로 쓰세요.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 임 × 신 (가을, 금생수) ───────────────────────
{
  month_pattern_id: '임_신', day_master: '임', month_branch: '신',
  season: '가을', element_interaction: '금생수',
  label: '임수 × 신월지 — 가을의 쇠가 큰 물을 새로이 솟아오르게 하는 충전의 자리',
  modules: [
    { module_id: '임_신_mindset', month_pattern_id: '임_신', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['쇠가 물을 만들어내듯 에너지가 보충되고 자신감이 자라는 시기입니다', '지치고 소모되었던 것을 회복하며 새 힘을 얻습니다', '충전의 시간을 충실히 보내면 다음 단계의 추진력이 됩니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_신_health', month_pattern_id: '임_신', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['에너지가 보충되는 시기이니 컨디션 회복에 집중하세요', '폐·호흡기 건강을 살피고 가을 공기를 깊이 쉬세요', '규칙적인 운동으로 체력을 끌어올리기 좋습니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_신_career', month_pattern_id: '임_신', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['충전된 에너지로 새로운 일을 시작하거나 밀린 일을 밀고 나가기 좋습니다', '전문성과 기술이 인정받는 시기입니다', '지식과 노하우를 체계적으로 정리하면 더 큰 기회가 열립니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_신_romance', month_pattern_id: '임_신', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['자신감이 돋보이는 시기입니다 — 적극적으로 다가가도 좋습니다', '전문적이거나 지적인 매력이 사람을 끕니다', '충전된 에너지가 관계에 긍정적으로 작용합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_신_wealth', month_pattern_id: '임_신', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['들어오는 흐름이 안정되는 시기입니다 — 전문성에서 오는 수입에 유리합니다', '모은 것을 굳건하게 지키고 불리기 시작하기 좋습니다', '보수적이되 전문성에 투자하는 것은 유리합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_신_relationships', month_pattern_id: '임_신', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['신뢰받는 위치에 서기 좋은 시기입니다 — 전문성이 인맥을 넓힙니다', '윗사람이나 전문가 그룹에서 인정을 받을 수 있습니다', '충전된 기운이 사람들에게 안정감을 줍니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_신_growth', month_pattern_id: '임_신', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['전문성과 기술을 한 단계 끌어올리기에 가장 좋은 시기입니다', '자격, 기술, 지식을 체계적으로 정리하세요', '충전의 시간을 배움에 투자하면 결실이 빠릅니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_신_must_do', month_pattern_id: '임_신', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['충전의 시간을 충실히 보내어 다음 추진의 밑거름으로 삼으세요', '전문성을 정리하고 인정받을 수 있는 자리를 만드세요'], closing: '쇠가 물을 만들어내듯 에너지가 보충되는 자리입니다 — 충전을 허투루 쓰지 말고 다음 도약의 기반으로 쌓으세요.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 임 × 유 (가을, 금생수) ───────────────────────
{
  month_pattern_id: '임_유', day_master: '임', month_branch: '유',
  season: '가을', element_interaction: '금생수',
  label: '임수 × 유월지 — 가을의 정금이 큰 물을 섬세하게 북돋는 자리',
  modules: [
    { module_id: '임_유_mindset', month_pattern_id: '임_유', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['신월보다 더 정밀하고 섬세한 충전의 시기입니다 — 내실을 다지세요', '넓게 퍼지려는 임수의 성향을 가다듬어 정밀하게 쓰기 좋습니다', '결실을 점검하고 남은 일을 끝맺는 데 집중하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_유_health', month_pattern_id: '임_유', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['건조한 가을 공기에 폐·피부가 건조해질 수 있습니다 — 보습과 수분을 챙기세요', '호흡기 건강에 유의하고 따뜻한 물을 자주 드세요', '규칙적인 수면으로 회복력을 높이세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_유_career', month_pattern_id: '임_유', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['정밀함과 섬세함이 인정받는 시기입니다 — 마무리와 품질 관리에 유리합니다', '평가와 인정이 따르는 자리에 설 수 있습니다', '큰 그림보다 디테일에 집중하면 성과가 납니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_유_romance', month_pattern_id: '임_유', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['섬세한 배려가 관계를 깊게 만드는 시기입니다', '격식을 차려 만나는 자리에서 인연이 깊어집니다', '말 한마디의 무게가 크니 진심을 담아 전하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_유_wealth', month_pattern_id: '임_유', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['결실을 점검하고 자산을 정리하기 좋은 시기입니다', '정밀한 재무 관리와 계획적 지출에 유리합니다', '들어온 것을 굳건하게 지키세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_유_relationships', month_pattern_id: '임_유', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['품격 있는 관계, 신뢰 깊은 소수와의 교류에 유리합니다', '격식과 예의를 갖추면 인정을 받습니다', '평가와 인정의 자리에서 겸손이 관계를 지킵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_유_growth', month_pattern_id: '임_유', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['마무리와 정제의 시기입니다 — 배운 것을 빈틈없이 다듬으세요', '세밀한 기술과 전문 지식의 품질을 높이세요', '결실을 돌아보며 다음을 설계하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_유_must_do', month_pattern_id: '임_유', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['넓게 퍼진 에너지를 가다듬어 정밀하게 쓰세요', '결실을 점검하고 남은 일을 끝맺으세요'], closing: '가을 정금이 물을 섬세하게 북돋듯, 넓은 흐름을 정제하여 결실로 묶는 자리입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 임 × 술 (가을, 토극수) ───────────────────────
{
  month_pattern_id: '임_술', day_master: '임', month_branch: '술',
  season: '가을', element_interaction: '토극수',
  label: '임수 × 술월지 — 가을의 마른 흙이 큰 물의 흐름을 강하게 막는 자리',
  modules: [
    { module_id: '임_술_mindset', month_pattern_id: '임_술', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['건조한 흙이 물의 흐름을 강하게 막는 시기입니다 — 제약과 압박이 큽니다', '억눌림이 심할 수 있으나 이것이 흐름을 바로잡는 기회이기도 합니다', '막힌 시간을 견디며 내면을 단련하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_술_health', month_pattern_id: '임_술', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['스트레스로 인한 위장·소화기 문제가 올 수 있습니다', '건조한 기운에 피부와 호흡기도 예민해집니다', '답답함을 풀기 위해 규칙적인 운동과 휴식을 병행하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_술_career', month_pattern_id: '임_술', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['규칙, 책임, 압박이 강한 환경에서 일하게 됩니다', '억지로 뚫으려 하지 말고 규칙 안에서 실력을 보여주세요', '인내의 시간이 다음 기회의 밑거름이 됩니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_술_romance', month_pattern_id: '임_술', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['관계에 제약이나 의무감이 무겁게 느껴질 수 있습니다', '책임을 피하지 말고 함께 나누는 것이 관계를 지킵니다', '억눌린 감정을 솔직히 나누되 비난이 되지 않게 하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_술_wealth', month_pattern_id: '임_술', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈의 흐름이 막히거나 지출에 제약이 생길 수 있습니다', '비상금을 굳건히 쥐고 불필요한 지출을 최소화하세요', '투자는 극히 보수적으로 접근하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_술_relationships', month_pattern_id: '임_술', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['관계의 의무와 책임이 무겁게 느껴지는 시기입니다', '맺고 끊는 것을 명확히 하여 에너지 새는 것을 막으세요', '소수의 신뢰할 수 있는 사람에게 기대세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_술_growth', month_pattern_id: '임_술', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['제약 속에서 인내와 규율을 배우는 시기입니다', '억눌림을 에너지로 바꾸는 훈련이 필요합니다', '정리와 반성의 시간을 가지세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_술_must_do', month_pattern_id: '임_술', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['강한 제약을 인내로 견디며 내면을 단련하세요', '억지로 뚫지 말고 규칙 안에서 실력을 쌓으세요'], closing: '건조한 흙이 물을 강하게 막는 자리입니다 — 막힘을 극복의 에너지로 바꾸는 인내가 숙제입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 임 × 해 (겨울, 수수비화) ─────────────────────
{
  month_pattern_id: '임_해', day_master: '임', month_branch: '해',
  season: '겨울', element_interaction: '수겹수',
  label: '임수 × 해월지 — 큰 물이 겨울 바다와 만나 흘러넘치는 자유의 자리',
  modules: [
    { module_id: '임_해_mindset', month_pattern_id: '임_해', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['같은 물이 합쳐 흐름이 커지는 시기입니다 — 자신감이 붇고 자유로워집니다', '너무 강해진 물이 범람할 수 있으니 중심을 잡는 것이 중요합니다', '자유를 즐기되 흩어지지 않도록 닻을 내리세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_해_health', month_pattern_id: '임_해', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['차가운 기운이 강해지니 몸을 따뜻하게 하세요 — 특히 신장·비뇨기 건강', '물이 너무 많아 몸이 무겁고 나른해질 수 있습니다', '따뜻한 차와 목욕으로 순환을 돕고 가벼운 운동으로 기운을 끌어올리세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_해_career', month_pattern_id: '임_해', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['에너지가 넘쳐 추진력이 강해지는 시기입니다 — 밀고 나가기 좋습니다', '다만 너무 많은 일에 손을 대면 범람하듯 흩어집니다', '강한 흐름을 한 방향으로 좁혀 집중하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_해_romance', month_pattern_id: '임_해', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['매력과 자신감이 넘치는 시기입니다 — 자연스럽게 사람을 끕니다', '너무 자유로운 흐름이 관계를 흩뜨릴 수 있으니 한 사람에게 집중하세요', '감정의 물살이 강하니 흥분 상태의 결정을 피하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_해_wealth', month_pattern_id: '임_해', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈의 흐름이 크고 빠릅니다 — 들어와도 나가기 쉬우니 저축을 우선하세요', '물이 넘치듯 기회가 많아 보이지만 과신은 금물입니다', '현금 흐름을 단단히 쥐고 분산 투자를 유지하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_해_relationships', month_pattern_id: '임_해', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['사람과의 흐름이 활발해지는 시기입니다 — 넓은 인맥이 형성됩니다', '너무 많은 관계에 에너지를 쓰면 핵심 인연이 흐려집니다', '강한 흐름 속에서도 한 발 관조하는 자세가 필요합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_해_growth', month_pattern_id: '임_해', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['에너지가 넘치는 시기이니 새로운 도전을 시작하기 좋습니다', '넓은 호기심을 따라가되 한두 가지로 좁히는 훈련이 필요합니다', '충전과 정비의 시간도 함께 가지세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_해_must_do', month_pattern_id: '임_해', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['넘치는 에너지를 한 방향으로 좁혀 집중하세요', '과신하여 범람하지 않도록 중심을 잡으세요'], closing: '같은 물이 합쳐 흐름이 커지는 자리입니다 — 자유의 힘을 흩어짐이 아닌 추진력으로 쓰는 것이 숙제입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 임 × 자 (겨울, 수수비화) ─────────────────────
{
  month_pattern_id: '임_자', day_master: '임', month_branch: '자',
  season: '겨울', element_interaction: '수겹수',
  label: '임수 × 자월지 — 한겨울 큰 물이 가장 왕성하게 솟구치는 절정의 자리',
  modules: [
    { module_id: '임_자_mindset', month_pattern_id: '임_자', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['물이 극도로 강해지는 시기입니다 — 임수가 가장 힘을 얻지만 동시에 범람 위험이 가장 큽니다', '자신감이 최고조이되, 과신이 가장 큰 적입니다', '강한 힘을 의식적으로 가다듬어 한 점으로 모으세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_자_health', month_pattern_id: '임_자', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['차가운 기운이 절정이니 몸을 가장 따뜻하게 하세요', '신장·비뇨기·생식기 건강에 각별히 유의하고 따뜻한 물을 자주 드세요', '수족 냉증과 순환 문제를 경계하세요 — 반신욕과 가벼운 운동이 좋습니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_자_career', month_pattern_id: '임_자', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['추진력과 결단력이 가장 강한 시기입니다 — 중요한 결정과 실행에 유리합니다', '다만 너무 강한 흐름이 주변과 충돌을 만들 수 있습니다', '힘을 쓰되 부드럽게 쓰는 것이 더 큰 결과를 만듭니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_자_romance', month_pattern_id: '임_자', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['강렬하고 주도적인 관계가 열립니다 — 자신감이 매력이 됩니다', '너무 밀어붙이면 상대가 압도되니 강도를 조절하세요', '감정이 강할수록 한 박자 쉬는 것이 관계를 지킵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_자_wealth', month_pattern_id: '임_자', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈의 흐름이 가장 크고 빠릅니다 — 범람하듯 흘러도 나갈 수 있습니다', '과신하여 큰 투자나 도박을 하면 위험합니다', '저축과 보존을 최우선으로 하고 현금을 굳건히 쥐세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_자_relationships', month_pattern_id: '임_자', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['주도권을 쥐기 쉬운 시기이되 너무 강하면 사람이 멀어집니다', '강한 흐름 속에서 듣는 귀를 더 무겁게 하세요', '한 발 물러서 관조하는 것이 인맥을 지킵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_자_growth', month_pattern_id: '임_자', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['가장 강한 에너지를 깊이 있는 집중에 쓰세요', '과신을 경계하고 겸손의 훈련이 필요합니다', '충전과 정비에 충분한 시간을 확보하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_자_must_do', month_pattern_id: '임_자', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['극도로 강한 에너지를 가다듬어 한 방향으로 모으세요', '과신과 범람을 경계하고 한 발 관조하세요'], closing: '한겨울 물이 절정에 이른 자리입니다 — 가장 강한 힘을 가장 정교하게 쓰는 것이 숙제입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 임 × 축 (겨울, 토극수-완화) ─────────────────
{
  month_pattern_id: '임_축', day_master: '임', month_branch: '축',
  season: '겨울', element_interaction: '토극수_완화',
  label: '임수 × 축월지 — 얼어붙은 겨울 흙이 큰 물을 가두고 잠재우는 자리',
  modules: [
    { module_id: '임_축_mindset', month_pattern_id: '임_축', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['차가운 흙이 물을 얼려 붙잡듯 흐름이 느려지고 침체되는 시기입니다', '답답함과 우울이 올 수 있으니 이 시간을 잠복과 충전으로 쓰세요', '견디는 시간이 봄의 에너지를 만듭니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_축_health', month_pattern_id: '임_축', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['한랭한 기운이 몸을 굳게 하니 관절·위장·순환에 유의하세요', '따뜻한 음식과 목욕으로 몸을 풀고 가벼운 운동으로 굳은 기운을 녹이세요', '우울과 무기력을 경계하고 햇빛을 자주 쐐세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_축_career', month_pattern_id: '임_축', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['일의 속도가 느려지고 답답함이 큰 시기입니다', '억지로 밀어붙이지 말고 정비와 준비의 시간으로 쓰세요', '내실을 다지면 봄에 속도가 붙습니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_축_romance', month_pattern_id: '임_축', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['관계가 답답하고 정체되기 쉬운 시기입니다', '억눌린 감정을 억지로 풀기보다 인내와 기다림이 필요합니다', '차분하게 함께 있는 시간이 관계를 지킵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_축_wealth', month_pattern_id: '임_축', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈의 흐름이 굳고 느려지는 시기입니다', '새로운 투자보다 보존과 정리에 집중하세요', '불필요한 지출을 줄이고 비상금을 굳건히 쥐세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_축_relationships', month_pattern_id: '임_축', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['관계가 정체되고 소통이 줄어들기 쉬운 시기입니다', '억지로 만남을 만들기보다 소수와 깊이 교류하세요', '차분한 시간이 관계의 깊이를 만듭니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_축_growth', month_pattern_id: '임_축', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['잠복과 충전의 시기입니다 — 겉으로 드러나지 않아도 내면이 자랍니다', '정리와 반성, 복습에 집중하세요', '우울을 경계하고 규칙적인 일상 리듬을 유지하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '임_축_must_do', month_pattern_id: '임_축', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['침체와 답답함을 인내하며 잠복의 시간을 충전에 쓰세요', '우울에 빠지지 않도록 규칙적인 일상과 햇빛을 챙기세요'], closing: '얼어붙은 흙이 물을 붙잡듯 흐름이 멈추는 자리입니다 — 멈춤을 정체가 아닌 잠복으로 쓰는 것이 숙제입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ============================================================
// 계수(癸) 일간 — 이슬·샘물 (음수)
// 스며들고 적시고 조용히 살피는 힘, 직관, 섬세함.
// 우울·침체 주의.
// ============================================================

// ── 계 × 인 (봄, 수생목) ──────────────────────────
{
  month_pattern_id: '계_인', day_master: '계', month_branch: '인',
  season: '봄', element_interaction: '수생목',
  label: '계수 × 인월지 — 이슬이 봄 새싹을 적시며 스며드는 자리',
  modules: [
    { module_id: '계_인_mindset', month_pattern_id: '계_인', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['이슬이 새싹을 적시듯 섬세하게 무언가를 돕고 키우는 데 보람이 있습니다', '직관과 감수성이 예민해지는 시기입니다 — 감정의 흐름을 관찰하세요', '크게 벌이기보다 가까운 곳에서부터 조용히 피워나가세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_인_health', month_pattern_id: '계_인', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['작은 물이 나무에 쓰이며 에너지가 소모됩니다 — 무리하지 말고 쉬세요', '간·피로가 올 수 있으니 봄나물과 따뜻한 차로 보살피세요', '신경이 예민해지니 충분한 수면이 중요합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_인_career', month_pattern_id: '계_인', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['섬세한 돌봄과 육성, 기획, 서비스 일에 에너지가 잘 맞습니다', '직관과 관찰력을 살려 틈새를 찾는 일에 유리합니다', '넓게 벌이지 말고 좁고 깊이 있는 일에 집중하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_인_romance', month_pattern_id: '계_인', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['섬세한 배려와 직관이 인연을 끌어당깁니다', '조용히 다가가는 만남이 좋습니다 — 강하게 밀어붙이지 마세요', '감수성이 풍부해져 공감 능력이 높아집니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_인_wealth', month_pattern_id: '계_인', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈이 서서히 쓰이며 흘러나갑니다 — 작은 지출도 무시하지 마세요', '씨앗에 투자하듯 돕고 기르는 일에 쓴 돈은 천천히 자랍니다', '감정적 소비를 경계하고 가계부를 쓰세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_인_relationships', month_pattern_id: '계_인', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['조용히 살피고 배려하는 태도가 사람을 끕니다', '소수와 깊이 교류하는 것이 편안합니다', '지나친 헌신으로 자신이 소진되지 않도록 선을 정하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_인_growth', month_pattern_id: '계_인', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['직관과 감수성을 기르기 좋은 시기입니다 — 예술, 글쓰기, 관찰', '배운 것을 조용히 자기 것으로 소화하는 시간이 필요합니다', '넓게보다 깊이 파고드는 학습이 맞습니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_인_must_do', month_pattern_id: '계_인', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['직관과 섬세함을 한 방향으로 모아 결과를 내세요', '에너지 소모를 경계하고 충분히 쉬세요'], closing: '이슬이 새싹을 적시듯 조용히 스며드는 자리입니다 — 섬세함을 쓰되 소진되지 않게 자신을 돌보세요.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 계 × 묘 (봄, 수생목) ──────────────────────────
{
  month_pattern_id: '계_묘', day_master: '계', month_branch: '묘',
  season: '봄', element_interaction: '수생목',
  label: '계수 × 묘월지 — 샘물이 무성한 봄꽃밭 속으로 스며드는 자리',
  modules: [
    { module_id: '계_묘_mindset', month_pattern_id: '계_묘', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['감수성과 예술적 감각이 가장 돋보이는 시기입니다', '정서적으로 깊이 빠져들기 쉬우니 한 발 떨어져 보는 균형이 필요합니다', '표현과 창작 욕구가 강합니다 — 감정을 작품으로 빚어보세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_묘_health', month_pattern_id: '계_묘', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['감정의 기복이 피로로 이어집니다 — 신경성 피로와 수면 부족을 조심하세요', '간·스트레스가 올 수 있으니 충분히 쉬고 가벼운 산책으로 기운을 푸세요', '감정을 억누르지 말고 건강하게 표현하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_묘_career', month_pattern_id: '계_묘', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['창작, 디자인, 예술, 문학, 콘텐츠 등 감각을 쓰는 일에 가장 유리합니다', '감각은 풍부하나 끝맺음이 약해질 수 있으니 마감 기한을 명확히 하세요', '협업에서 조율 능력이 빛을 발합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_묘_romance', month_pattern_id: '계_묘', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['매력과 감수성이 가장 돋보이는 시기입니다 — 낭만적인 만남이 열립니다', '감정에 깊이 빠지면 객관성을 잃으니 한 발 떨어져 보세요', '예술적이고 감성적인 자리에서 인연이 닿습니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_묘_wealth', month_pattern_id: '계_묘', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['감정적 소비가 가장 유혹적인 시기입니다 — 충동 구매를 경계하세요', '예술과 감각에 투자하면 천천히 결실이 옵니다', '감정이 출렁일 때는 지출을 미루세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_묘_relationships', month_pattern_id: '계_묘', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['사람을 끌어당히는 힘이 강하지만 관계의 감정적 소용돌이에 휩쓸리지 마세요', '공감 능력이 높아지되 자기 감정을 잃지 않는 것이 중요합니다', '깊이 있는 소수의 관계가 편안합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_묘_growth', month_pattern_id: '계_묘', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['예술, 미학, 문학 등 감각적 영역의 성장이 가장 큽니다', '감정을 기록하는 일기, 글쓰기가 내면을 정돈합니다', '감수성을 작품으로 표현하면 앎이 깊어집니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_묘_must_do', month_pattern_id: '계_묘', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['감정에 휩쓸리지 않고 객관적 중심을 잡으세요', '감수성을 결과물로 빚어내세요'], closing: '샘물이 꽃밭에 스며들듯 감수성이 절정인 자리입니다 — 빠져드는 힘을 작품으로 승화시키세요.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 계 × 진 (봄, 토극수-완화) ───────────────────
{
  month_pattern_id: '계_진', day_master: '계', month_branch: '진',
  season: '봄', element_interaction: '토극수_완화',
  label: '계수 × 진월지 — 축축한 봄흙이 이슬을 흠뻑 품어 저장하는 자리',
  modules: [
    { module_id: '계_진_mindset', month_pattern_id: '계_진', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['축축한 흙이 작은 물을 흠뻑 품듯 안정감이 자리를 잡는 시기입니다', '흩어지려던 감정이 모이고 뿌리가 내립니다', '모으고 정리하는 마음으로 움직이세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_진_health', month_pattern_id: '계_진', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['습기가 몸에 차게 고이기 쉬우니 비·신장·위장을 살피세요', '가벼운 운동으로 습기를 풀고 따뜻한 차로 순환을 도우세요', '충분한 휴식으로 감정의 안정을 챙기세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_진_career', month_pattern_id: '계_진', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['정리, 저장, 문서 관리에 유리한 시기입니다', '흩어진 일과 자산을 모아 체계화하면 성과가 납니다', '안정적 환경에서 신뢰를 쌓기 좋습니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_진_romance', month_pattern_id: '계_진', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['관계가 안정적으로 자리 잡는 시기입니다 — 진지한 인연이 깊어집니다', '함께 모아가는 관계가 편안합니다', '감정의 흔들림이 가라앉으니 신뢰를 다지세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_진_wealth', month_pattern_id: '계_진', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['저축과 자산 형성에 매우 유리한 자리입니다', '작은 돈도 모이면 큰 자산이 됩니다 — 꾸준히 저축하세요', '지출을 줄이고 저축 비율을 높이세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_진_relationships', month_pattern_id: '계_진', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['신뢰 깊은 소수와의 관계가 편안하고 이로운 시기입니다', '가족과 함께 시간을 보내며 뿌리를 내리세요', '넓은 인맥보다 좁고 단단한 관계가 도움이 됩니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_진_growth', month_pattern_id: '계_진', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['배운 것을 체계적으로 정리하고 저장하기 좋은 시기입니다', '한 주제를 깊이 파고드는 몰입의 시간을 만드세요', '지식을 자산으로 묶어 내는 작업이 잘 풀립니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_진_must_do', month_pattern_id: '계_진', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['흩어진 감정과 에너지를 모아 안정의 토대를 만드세요', '저축과 정리에 집중하세요'], closing: '축축한 흙이 이슬을 품듯 작은 물이 머물러 결실의 토대가 되는 자리입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 계 × 사 (여름, 수극화) ───────────────────────
{
  month_pattern_id: '계_사', day_master: '계', month_branch: '사',
  season: '여름', element_interaction: '수극화',
  label: '계수 × 사월지 — 작은 이슬이 초여름 불에 닿아 증발을 두려워하는 자리',
  modules: [
    { module_id: '계_사_mindset', month_pattern_id: '계_사', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['작은 물이 큰 불 앞에 선 시기입니다 — 긴장과 소진 위험이 큽니다', '맞서기보다 한 발 물러서서 서늘하게 대처하는 것이 유리합니다', '에너지 관리가 생존의 열쇠입니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_사_health', month_pattern_id: '계_사', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['물이 빨리 마르듯 에너지 소진이 큽니다 — 수분 보충과 휴식이 최우선입니다', '심장·혈액순환에 유의하고 더위를 피하세요', '밤늦게 활동을 줄이고 서늘한 환경에서 쉬세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_사_career', month_pattern_id: '계_사', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['정면 경쟁보다 우회와 섬세함이 유리한 시기입니다', '통찰을 조용히 제안하는 방식이 효과적입니다', '무리한 추진은 소진을 부르니 속도를 조절하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_사_romance', month_pattern_id: '계_사', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['감정이 격해지기 쉬운 시기입니다 — 한 박자 늦추세요', '섬세한 배려가 매력이 되되 너무 얽매이면 답답해집니다', '서늘한 거리 조절이 관계를 지킵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_사_wealth', month_pattern_id: '계_사', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈이 빠르게 빠져나가기 쉬운 시기입니다 — 지출을 최소화하세요', '감정적 소비와 충동 투자가 가장 위험합니다', '현금을 굳건히 쥐고 가을까지 보존하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_사_relationships', month_pattern_id: '계_사', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['감정이 예민해져 말과 행동이 날카로워질 수 있습니다', '한 박자 쉬고 말하세요 — 흥분 상태의 말은 되돌리기 어렵습니다', '서늘하고 조용한 만남이 편안합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_사_growth', month_pattern_id: '계_사', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['에너지 관리와 자기 보호가 올해의 핵심 배움입니다', '긴장 속에서 인내와 절제를 기르세요', '혼자만의 정리 시간을 의식적으로 만드세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_사_must_do', month_pattern_id: '계_사', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['에너지 소진을 막고 한 발 물러서서 서늘하게 대처하세요', '정면 경쟁을 피하고 우회를 택하세요'], closing: '작은 이슬이 불 앞에 선 자리입니다 — 맞서지 말고 피하며, 서늘함을 지키는 것이 숙제입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 계 × 오 (여름, 수극화) ───────────────────────
{
  month_pattern_id: '계_오', day_master: '계', month_branch: '오',
  season: '여름', element_interaction: '수극화',
  label: '계수 × 오월지 — 한낮의 태양 앞에서 이슬이 가장 치열하게 마르는 자리',
  modules: [
    { module_id: '계_오_mindset', month_pattern_id: '계_오', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['이슬이 한낮의 태양에 마르듯 가장 치열한 소진의 시기입니다', '버티기보다 서늘한 곳으로 물러서는 것이 지혜입니다', '이 시기를 견디면 가을에 충전이 옵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_오_health', month_pattern_id: '계_오', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['체력 소모가 가장 큰 시기입니다 — 수분 보충과 휴식이 절대적으로 우선입니다', '심장·혈압·눈 건강에 유의하고 한낮 활동을 피하세요', '수면 부족이 면역력을 떨어뜨리니 규칙적으로 쉬세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_오_career', month_pattern_id: '계_오', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['치열한 환경에서 소진이 큽니다 — 정면 승부보다 우회가 유리합니다', '섬세함과 직관을 무기로 틈새를 공략하세요', '과로를 피하고 일의 속도를 조절하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_오_romance', month_pattern_id: '계_오', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['감정이 가장 격해지는 시기입니다 — 흥분 상태의 결정을 피하세요', '서늘한 거리가 관계를 지키고 매력을 높입니다', '너무 얽매이면 소진이 크니 적당한 공간이 필요합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_오_wealth', month_pattern_id: '계_오', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈이 빠르게 마르는 시기입니다 — 지출을 최소화하고 보존에 집중하세요', '투기와 충동 소비가 가장 위험합니다', '현금을 굳건히 쥐고 큰 지출은 가을로 미루세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_오_relationships', month_pattern_id: '계_오', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['감정이 가장 격해지는 시기입니다 — 말과 행동을 한 박자 늦추세요', '실수한 말은 치명적이 될 수 있습니다', '서늘하고 조용한 만남만 유지하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_오_growth', month_pattern_id: '계_오', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['치열한 환경에서 배우는 인내와 절제가 가장 큰 배움입니다', '에너지 관리 자체가 학습입니다', '혼자만의 정리 시간을 의식적으로 확보하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_오_must_do', month_pattern_id: '계_오', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['소진을 막고 서늘한 곳으로 물러서세요', '체력 관리와 자기 보호를 최우선으로 하세요'], closing: '한낮 태양 앞의 이슬이 가장 치열하게 마르는 자리입니다 — 버티지 말고 물러서며, 가을의 충전을 위해 자신을 지키세요.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 계 × 미 (여름, 토극수) ───────────────────────
{
  month_pattern_id: '계_미', day_master: '계', month_branch: '미',
  season: '여름', element_interaction: '토극수',
  label: '계수 × 미월지 — 여름의 마른 흙이 작은 물을 빨아들이며 마르게 하는 자리',
  modules: [
    { module_id: '계_미_mindset', month_pattern_id: '계_미', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['마른 흙이 작은 물을 빨아들이듯 에너지가 갉아먹히는 시기입니다', '답답함과 무기력이 올 수 있으니 자신을 보호하는 데 집중하세요', '막힌 시간을 견디며 가을의 충전을 준비하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_미_health', month_pattern_id: '계_미', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['위장과 소화기가 예민해집니다 — 더위와 습기를 함께 조심하세요', '스트레스성 위염, 설사를 경계하고 식사를 규칙적으로', '충분한 수분과 가벼운 운동으로 기운을 순환시키세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_미_career', month_pattern_id: '계_미', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['규칙과 제약이 많아 소진이 큰 환경입니다', '억지로 뚫지 말고 조용히 내실을 다지세요', '상반기를 정리하고 하반기를 준비하는 데 유리합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_미_romance', month_pattern_id: '계_미', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['관계에서 답답함과 의무감이 큰 시기입니다', '억눌린 감정을 억지로 풀기보다 인내가 필요합니다', '서로의 공간을 존중하며 차분하게 함께하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_미_wealth', month_pattern_id: '계_미', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈의 흐름이 느리고 제약이 생길 수 있습니다', '지출을 최소화하고 비상금을 확보하세요', '투기는 절대 피하고 보존에 집중하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_미_relationships', month_pattern_id: '계_미', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['관계의 의무와 부담이 크게 느껴지는 시기입니다', '맺고 끊는 것을 명확히 하여 에너지 새는 것을 막으세요', '소수의 신뢰할 수 있는 사람에게만 의지하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_미_growth', month_pattern_id: '계_미', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['제약 속에서 인내를 기르는 시기입니다', '막힘을 겪으며 배우는 것이 나중에 자산이 됩니다', '정리와 반성의 시간을 가지세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_미_must_do', month_pattern_id: '계_미', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['답답함과 소진을 견디며 자신을 보호하세요', '억지로 뚫지 말고 조용히 내실을 다지세요'], closing: '마른 흙이 작은 물을 빨아들이는 자리입니다 — 막힘을 견디며 가을의 충전을 준비하세요.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 계 × 신 (가을, 금생수) ───────────────────────
{
  month_pattern_id: '계_신', day_master: '계', month_branch: '신',
  season: '가을', element_interaction: '금생수',
  label: '계수 × 신월지 — 가을의 쇠가 마른 이슬을 새로이 솟아오르게 하는 충전의 자리',
  modules: [
    { module_id: '계_신_mindset', month_pattern_id: '계_신', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['여름의 소진에서 벗어나 에너지가 보충되는 시기입니다 — 회복과 충전', '자신감이 자라며 마음이 단단해집니다', '충전의 시간을 충실히 보내면 다음 추진의 밑거름이 됩니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_신_health', month_pattern_id: '계_신', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['컨디션 회복에 집중하기 좋은 시기입니다', '폐·호흡기 건강을 살피고 가을 공기를 깊이 쉬세요', '규칙적인 운동으로 체력을 끌어올리세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_신_career', month_pattern_id: '계_신', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['충전된 에너지로 새로운 일을 시작하거나 밀린 일을 밀기 좋습니다', '전문성과 기술이 인정받는 시기입니다', '지식을 체계적으로 정리하면 더 큰 기회가 열립니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_신_romance', month_pattern_id: '계_신', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['자신감이 돋보이는 시기입니다 — 적극적으로 다가가도 좋습니다', '전문적이거나 지적인 매력이 사람을 끕니다', '충전된 에너지가 관계에 긍정적으로 작용합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_신_wealth', month_pattern_id: '계_신', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['들어오는 흐름이 안정되는 시기입니다 — 전문성에서 오는 수입에 유리합니다', '모은 것을 굳건하게 지키고 불리기 시작하세요', '보수적이되 전문성에 투자하는 것은 유리합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_신_relationships', month_pattern_id: '계_신', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['신뢰받는 위치에 서기 좋은 시기입니다 — 전문성이 인맥을 넓힙니다', '윗사람이나 전문가 그룹에서 인정을 받을 수 있습니다', '충전된 기운이 사람들에게 안정감을 줍니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_신_growth', month_pattern_id: '계_신', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['전문성과 기술을 한 단계 끌어올리기에 좋은 시기입니다', '자격, 기술, 지식을 체계적으로 정리하세요', '충전의 시간을 배움에 투자하면 결실이 빠릅니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_신_must_do', month_pattern_id: '계_신', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['충전의 시간을 충실히 보내어 다음 추진의 밑거름으로 삼으세요', '전문성을 정리하고 인정받을 수 있는 자리를 만드세요'], closing: '쇠가 마른 이슬을 새로이 솟게 하는 충전의 자리입니다 — 충전을 허투루 쓰지 말고 다음 도약의 기반으로 쌓으세요.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 계 × 유 (가을, 금생수) ───────────────────────
{
  month_pattern_id: '계_유', day_master: '계', month_branch: '유',
  season: '가을', element_interaction: '금생수',
  label: '계수 × 유월지 — 가을 정금이 샘물을 정밀하게 솟게 하는 섬세한 충전의 자리',
  modules: [
    { module_id: '계_유_mindset', month_pattern_id: '계_유', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['신월보다 더 정밀하고 섬세한 충전의 시기입니다 — 결실을 점검하고 정제하세요', '직관과 섬세함이 최고조에 이릅니다', '남은 일을 끝맺고 품질을 높이는 데 집중하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_유_health', month_pattern_id: '계_유', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['건조한 가을 공기에 피부와 폐가 예민해집니다 — 보습과 수분을 챙기세요', '호흡기 건강에 유의하고 따뜻한 물을 자주 드세요', '규칙적인 수면으로 회복력을 높이세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_유_career', month_pattern_id: '계_유', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['정밀함과 섬세함이 인정받는 시기입니다 — 마무리와 품질 관리에 유리합니다', '평가와 인정이 따르는 자리에 설 수 있습니다', '디테일에 집중하면 성과가 납니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_유_romance', month_pattern_id: '계_유', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['섬세한 배려와 진심이 관계를 깊게 만드는 시기입니다', '격식을 차려 만나는 자리에서 인연이 깊어집니다', '말 한마디의 무게가 크니 진심을 담아 전하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_유_wealth', month_pattern_id: '계_유', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['결실을 점검하고 자산을 정리하기 좋은 시기입니다', '정밀한 재무 관리와 계획적 지출에 유리합니다', '들어온 것을 굳건하게 지키세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_유_relationships', month_pattern_id: '계_유', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['품격 있고 신뢰 깊은 소수와의 교류에 유리합니다', '격식과 예의를 갖추면 인정을 받습니다', '평가와 인정의 자리에서 겸손이 관계를 지킵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_유_growth', month_pattern_id: '계_유', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['마무리와 정제의 시기입니다 — 배운 것을 빈틈없이 다듬으세요', '세밀한 기술과 전문 지식의 품질을 높이세요', '결실을 돌아보며 다음을 설계하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_유_must_do', month_pattern_id: '계_유', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['직관과 섬세함을 결실로 묶어내세요', '남은 일을 끝맺고 품질을 높이세요'], closing: '가을 정금이 샘물을 정밀하게 솟게 하는 자리입니다 — 섬세함을 빈틈없는 결실로 승화시키세요.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 계 × 술 (가을, 토극수) ───────────────────────
{
  month_pattern_id: '계_술', day_master: '계', month_branch: '술',
  season: '가을', element_interaction: '토극수',
  label: '계수 × 술월지 — 가을의 마른 흙이 작은 샘물을 강하게 막고 마르게 하는 자리',
  modules: [
    { module_id: '계_술_mindset', month_pattern_id: '계_술', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['마른 흙이 샘물을 빨아들이듯 가장 억눌리고 마르는 시기입니다', '답답함과 무기력이 클 수 있으니 자신을 지키는 데 집중하세요', '이 시기를 견디면 겨울에 힘이 돌아옵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_술_health', month_pattern_id: '계_술', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['스트레스로 인한 위장·소화기 문제가 올 수 있습니다', '건조한 기운에 피부와 호흡기도 예민해집니다', '답답함을 풀기 위해 규칙적인 운동과 휴식을 병행하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_술_career', month_pattern_id: '계_술', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['규칙, 책임, 압박이 강한 환경에서 일하게 됩니다', '억지로 뚫지 말고 규칙 안에서 조용히 실력을 보여주세요', '인내의 시간이 겨울의 충전으로 이어집니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_술_romance', month_pattern_id: '계_술', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['관계에 제약과 의무가 무겁게 느껴지는 시기입니다', '책임을 피하지 말고 함께 나누세요', '억눌린 감정을 솔직히 나누되 비난이 되지 않게 하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_술_wealth', month_pattern_id: '계_술', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈의 흐름이 막히거나 지출에 제약이 생길 수 있습니다', '비상금을 굳건히 쥐고 불필요한 지출을 최소화하세요', '투자는 극히 보수적으로 접근하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_술_relationships', month_pattern_id: '계_술', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['관계의 의무와 책임이 무겁게 느껴지는 시기입니다', '맺고 끊는 것을 명확히 하여 에너지 새는 것을 막으세요', '소수의 신뢰할 수 있는 사람에게만 기대세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_술_growth', month_pattern_id: '계_술', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['제약 속에서 인내와 규율을 배우는 시기입니다', '억눌림을 에너지로 바꾸는 훈련이 필요합니다', '정리와 반성의 시간을 가지세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_술_must_do', month_pattern_id: '계_술', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['강한 제약을 인내로 견디며 자신을 보호하세요', '억지로 뚫지 말고 규칙 안에서 실력을 쌓으세요'], closing: '마른 흙이 작은 샘물을 강하게 막는 자리입니다 — 막힘을 견디며 겨울의 충전을 향해 나아가세요.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 계 × 해 (겨울, 수수비화) ─────────────────────
{
  month_pattern_id: '계_해', day_master: '계', month_branch: '해',
  season: '겨울', element_interaction: '수겹수',
  label: '계수 × 해월지 — 작은 이슬이 큰 겨울 물과 합류하며 강해지는 자리',
  modules: [
    { module_id: '계_해_mindset', month_pattern_id: '계_해', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['작은 물이 큰 물에 합류하듯 자신감이 붇고 힘이 커지는 시기입니다', '평소의 섬세함에 추진력이 더해집니다', '강해진 만큼 중심을 잃지 않도록 닻을 내리세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_해_health', month_pattern_id: '계_해', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['차가운 기운이 강해지니 몸을 따뜻하게 하세요 — 특히 신장·비뇨기', '물이 많아 몸이 무겁고 나른해질 수 있습니다', '따뜻한 차와 목욕으로 순환을 돕고 가벼운 운동으로 기운을 끌어올리세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_해_career', month_pattern_id: '계_해', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['추진력이 강해지는 시기입니다 — 밀고 나가기 좋습니다', '다만 너무 많은 일에 손을 대면 흩어집니다', '강한 흐름을 한 방향으로 좁혀 집중하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_해_romance', month_pattern_id: '계_해', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['매력과 자신감이 커지는 시기입니다 — 자연스럽게 사람을 끕니다', '너무 자유로운 흐름이 관계를 흩뜨릴 수 있으니 한 사람에게 집중하세요', '강해진 감정의 물살을 의식적으로 조절하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_해_wealth', month_pattern_id: '계_해', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈의 흐름이 커지고 빨라집니다 — 들어와도 나가기 쉬우니 저축을 우선하세요', '물이 넘치듯 기회가 많아 보이지만 과신은 금물입니다', '현금 흐름을 단단히 쥐고 분산 투자를 유지하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_해_relationships', month_pattern_id: '계_해', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['사람과의 흐름이 활발해지는 시기입니다 — 넓은 인맥이 형성됩니다', '너무 많은 관계에 에너지를 쓰면 핵심 인연이 흐려집니다', '강한 흐름 속에서도 한 발 관조하는 자세가 필요합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_해_growth', month_pattern_id: '계_해', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['에너지가 넘치는 시기이니 새로운 도전을 시작하기 좋습니다', '넓은 호기심을 따라가되 한두 가지로 좁히는 훈련이 필요합니다', '충전과 정비의 시간도 함께 가지세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_해_must_do', month_pattern_id: '계_해', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['강해진 에너지를 한 방향으로 좁혀 집중하세요', '평소의 섬세함과 새로 얻은 추진력의 균형을 잡으세요'], closing: '작은 이슬이 큰 물에 합류하는 자리입니다 — 강해진 힘을 흩어짐이 아닌 집중으로 쓰세요.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 계 × 자 (겨울, 수수비화) ─────────────────────
{
  month_pattern_id: '계_자', day_master: '계', month_branch: '자',
  season: '겨울', element_interaction: '수겹수',
  label: '계수 × 자월지 — 한겨울 작은 물이 가장 왕성한 물과 만나 절정에 이르는 자리',
  modules: [
    { module_id: '계_자_mindset', month_pattern_id: '계_자', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['물의 기운이 절정에 이르러 가장 강해지는 시기입니다', '평소의 조용함이 큰 추진력으로 바뀝니다', '강해진 만큼 과신과 범람을 경계해야 합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_자_health', month_pattern_id: '계_자', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['차가운 기운이 절정이니 몸을 가장 따뜻하게 하세요', '신장·비뇨기·생식기 건강에 각별히 유의하고 따뜻한 물을 자주 드세요', '수족 냉증과 순환 문제를 경계하세요 — 반신욕과 가벼운 운동이 좋습니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_자_career', month_pattern_id: '계_자', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['추진력과 결단력이 가장 강한 시기입니다 — 중요한 결정과 실행에 유리합니다', '너무 강한 흐름이 주변과 충돌을 만들 수 있습니다', '힘을 쓰되 부드럽게 쓰는 것이 더 큰 결과를 만듭니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_자_romance', month_pattern_id: '계_자', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['강렬하고 주도적인 관계가 열립니다 — 자신감이 매력이 됩니다', '너무 밀어붙이면 상대가 압도되니 강도를 조절하세요', '감정이 강할수록 한 박자 쉬는 것이 관계를 지킵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_자_wealth', month_pattern_id: '계_자', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈의 흐름이 가장 크고 빠릅니다 — 범람하듯 흘러도 나갈 수 있습니다', '과신하여 큰 투자나 도박을 하면 위험합니다', '저축과 보존을 최우선으로 하고 현금을 굳건히 쥐세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_자_relationships', month_pattern_id: '계_자', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['주도권을 쥐기 쉬운 시기이되 너무 강하면 사람이 멀어집니다', '강한 흐름 속에서 듣는 귀를 더 무겁게 하세요', '한 발 물러서 관조하는 것이 인맥을 지킵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_자_growth', month_pattern_id: '계_자', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['가장 강한 에너지를 깊이 있는 집중에 쓰세요', '과신을 경계하고 겸손의 훈련이 필요합니다', '충전과 정비에 충분한 시간을 확보하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_자_must_do', month_pattern_id: '계_자', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['절정에 이른 에너지를 가다듬어 한 방향으로 모으세요', '과신과 범람을 경계하고 한 발 관조하세요'], closing: '한겨울 물이 절정에 이른 자리입니다 — 가장 강한 힘을 가장 정교하게 쓰는 것이 숙제입니다.', tone: 'natural', review_status: 'approved' },
  ],
},

// ── 계 × 축 (겨울, 토극수-완화) ─────────────────
{
  month_pattern_id: '계_축', day_master: '계', month_branch: '축',
  season: '겨울', element_interaction: '토극수_완화',
  label: '계수 × 축월지 — 얼어붙은 겨울 흙이 작은 물을 가두고 잠재우는 자리',
  modules: [
    { module_id: '계_축_mindset', month_pattern_id: '계_축', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
      points: ['차가운 흙이 물을 얼려 붙잡듯 흐름이 느려지고 가장 침체되는 시기입니다', '우울과 무기력이 가장 큰 위험입니다 — 이 시간을 잠복으로 쓰세요', '햇빛과 따뜻함을 의식적으로 찾아야 합니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_축_health', month_pattern_id: '계_축', domain_key: 'health', domain_label: '건강', domain_index: 2,
      points: ['한랭한 기운이 몸을 굳게 하니 관절·위장·순환에 유의하세요', '따뜻한 음식과 목욕으로 몸을 풀고 가벼운 운동으로 굳은 기운을 녹이세요', '우울과 무기력을 경계하고 햇빛을 자주 쐬세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_축_career', month_pattern_id: '계_축', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
      points: ['일의 속도가 가장 느려지고 답답함이 큰 시기입니다', '억지로 밀어붙이지 말고 정비와 준비의 시간으로 쓰세요', '내실을 다지면 봄에 속도가 붙습니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_축_romance', month_pattern_id: '계_축', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
      points: ['관계가 가장 답답하고 정체되기 쉬운 시기입니다', '억눌린 감정을 억지로 풀기보다 인내와 기다림이 필요합니다', '차분하게 함께 있는 시간이 관계를 지킵니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_축_wealth', month_pattern_id: '계_축', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
      points: ['돈의 흐름이 가장 굳고 느려지는 시기입니다', '새로운 투자보다 보존과 정리에 집중하세요', '불필요한 지출을 줄이고 비상금을 굳건히 쥐세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_축_relationships', month_pattern_id: '계_축', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
      points: ['관계가 정체되고 소통이 가장 줄어들기 쉬운 시기입니다', '억지로 만남을 만들기보다 소수와 깊이 교류하세요', '차분한 시간이 관계의 깊이를 만듭니다'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_축_growth', month_pattern_id: '계_축', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
      points: ['잠복과 충전의 시기입니다 — 겉으로 드러나지 않아도 내면이 자랍니다', '정리와 반성, 복습에 집중하세요', '우울을 경계하고 규칙적인 일상 리듬을 유지하세요'], closing: null, tone: 'natural', review_status: 'approved' },
    { module_id: '계_축_must_do', month_pattern_id: '계_축', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
      points: ['침체와 우울을 견디며 잠복의 시간을 충전에 쓰세요', '햇빛과 따뜻함을 의식적으로 찾아 우울을 떨치세요'], closing: '얼어붙은 흙이 작은 물을 붙잡는 자리입니다 — 멈춤을 정체가 아닌 잠복으로 쓰고, 봄을 향해 자신을 지키세요.', tone: 'natural', review_status: 'approved' },
  ],
},

] }; // end MONTH_IM_GYE
