// server/storage/seeds/month-mu-gi.mjs
// 월지 패턴 시드: 무토(戊) · 기토(己) 일간 × 12월지 = 24패턴
// 기준: 자평명리 일간 · 월지 오행 상호작용. 격국 · 용신 · 조후는 이 버전에서 다루지 않는다.
// 톤: 2인칭 처방적, 한자 최소화(첫 등장 시만 괄호 보조), 명리 용어 일상어 의역, 사건 예측 금지.

export const MONTH_MU_GI = {
  patterns: [

    // ══════════════════════════════════════════════════════════════════
    // 무토(戊) — 산, 큰 흙 (양토) × 12월지
    // 이미지: 버티고 지키고 누르는 힘, 신뢰, 묵직함. 고집 · 답답함 주의.
    // ══════════════════════════════════════════════════════════════════

    // ── 무_인: 봄, 목극토(극) ──
    {
      month_pattern_id: '무_인', day_master: '무', month_branch: '인',
      season: '봄',
      element_interaction: '극 (목극토) — 큰 나무가 산을 뚫고 뿌리를 내림, 흙이 상함',
      label: '무토 × 인월 — 큰 나무가 산을 뚫고 자라는 달, 압박 속에서 뼈대가 선다',
      modules: [
        { module_id: '무_인_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '압박을 버티는 힘을 기르세요 — 산은 나무 뿌리에 눌려도 무너지지 않습니다',
            '책임이 클수록 성장도 큽니다. 정면으로 맞서되, 먼저 기준을 세우세요',
            '고집으로 버티기보다 원칙으로 버티세요. 막무가내는 답답함을 부릅니다',
            '압박을 위협이 아니라 단련의 재료로 받아들이세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_인_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '나무 기운이 위장을 누르니 소화기 · 위장 관리가 최우선입니다',
            '긴장성 두통, 어깨 · 목 뭉침이 올 수 있습니다 — 의식적으로 풀어주세요',
            '등산, 웨이트트레이닝 등 묵직하게 땀을 흘리는 운동이 잘 맞습니다',
            '수면 부족과 과로가 가장 큰 적입니다 — 규칙적으로 쉬세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_인_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '책임지는 역할, 권한이 주어지는 환경에서 단련됩니다',
            '시험, 승진 심사 등 기준이 명확한 곳에서 실력을 증명하기 좋습니다',
            '작은 규정이라도 지키는 것이 신뢰를 지키는 길입니다',
            '체계와 원칙이 있는 조직에서 빛을 발합니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_인_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '기준이 강하고 책임감 있는 인연이 다가올 수 있습니다',
            '상대의 기준이 압박으로 느껴지면 솔직하게 대화로 조율하세요',
            '관계에서 주도권을 다투지 마세요 — 존중이 우선입니다',
            '빠른 발전보다 서로의 기준을 확인하는 시간이 필요합니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_인_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '압박 속에서 재물을 지키는 것이 핵심입니다 — 충동적 지출은 금물',
            '저축과 보존에 집중하세요 — 투자는 보수적으로',
            '문서, 계약은 한 번 더 확인하는 습관이 재물을 지킵니다',
            '큰 돈거래, 보증은 피하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_인_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '윗사람에게 요구를 받는 일이 많을 수 있습니다 — 경계를 분명히 하세요',
            '의견 충돌에서 한 발 물러서는 것이 관계를 지킵니다',
            '강한 인연이 들어오되, 존중받는 관계인지가 가장 중요합니다',
            '적을 만들지 않되, 끌려다니지도 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_인_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '압박을 성장의 재료로 쓰세요 — 책임이 클수록 배우는 것이 많습니다',
            '체력이 받쳐야 버틸 수 있습니다. 수면과 식사를 규칙적으로',
            '멘토나 지도자의 조언을 받아들이면 압박이 방향으로 바뀝니다',
            '기준과 원칙을 세우는 연습이 평생의 뼈대가 됩니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_인_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '책임 앞에서 기준부터 세우세요',
            '소화기 건강을 매일 챙기세요',
            '경쟁과 마찰에서는 한 발 물러서세요',
          ],
          closing: '압박을 뼈대로 바꾸는 사람이 인정을 얻습니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 무_묘: 봄, 목극토(극) ──
    {
      month_pattern_id: '무_묘', day_master: '무', month_branch: '묘',
      season: '봄',
      element_interaction: '극 (목극토) — 짙은 숲이 산을 뒤덮음, 은밀하고 질긴 제약',
      label: '무토 × 묘월 — 숲이 산을 덮는 달, 끈질긴 제약 속에서 인내가 빛난다',
      modules: [
        { module_id: '무_묘_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '겉보기엔 부드러운 제약이 속으로는 질긴 압박으로 다가옵니다',
            '인내가 필요한 시기입니다 — 서두르면 얽힘이 더 심해집니다',
            '산이 숲에 덮이면 본래 모습이 가려집니다. 내 중심을 잃지 마세요',
            '눈에 보이지 않는 압박을 인정하고, 차분하게 대응하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_묘_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '나무 기운이 위장을 지속적으로 누르니 만성 소화 불량, 위염을 조심하세요',
            '스트레스가 서서히 쌓이는 형태입니다 — 풀어내는 시간을 의식적으로 만드세요',
            '잔뜩 긴장한 몸을 풀기 위해 요가, 명상, 가벼운 산책이 좋습니다',
            '수면 전 마음을 비우는 습관이 스트레스 해소에 도움이 됩니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_묘_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '규칙과 제약이 많은 환경이 답답하게 느껴질 수 있습니다',
            '그러나 제약은 곧 기준입니다 — 기준 안에서 실력을 쌓으면 인정이 따라옵니다',
            '꼼꼼함과 인내심이 보람으로 돌아오는 시기입니다',
            '복잡한 일보다 단순하고 명확한 업무가 효율적입니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_묘_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '은밀하고 끈질긴 인연이 다가올 수 있습니다 — 겉모습에 속지 마세요',
            '관계에서 끈적한 갈등이 생기면 정면 돌파보다 시간을 두고 푸세요',
            '기준이 맞는지 확인하는 데 충분한 시간을 들이세요',
            '오해가 쌓이지 않도록 대화로 미리 풀어야 합니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_묘_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '재물의 흐름이 느리고 얽혀 있을 수 있습니다 — 서두르지 마세요',
            '복잡한 계약, 공동 투자는 피하세요 — 얽힘이 손실로 이어집니다',
            '확실하고 단순한 형태로 재물을 관리하세요',
            '문서의 세부 조건을 놓치지 않도록 꼼꼼히 확인하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_묘_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '미묘한 갈등이 얽혀 있는 시기입니다 — 직접적으로 부딪히지 마세요',
            '사람의 말 뒤에 뜻이 있을 수 있으니 잘 들어주세요',
            '가까운 사람과의 오해가 쌓이지 않도록 대화하세요',
            '관계를 단순하게 유지하면 얽힘이 줄어듭니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_묘_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '제약 속에서 인내를 기르는 것이 이 시기의 성장입니다',
            '얽힘을 푸는 연습 — 복잡한 것을 단순하게 보는 눈을 기르세요',
            '배움의 속도가 느려 보여도, 쌓이면 단단해집니다',
            '제약을 기준으로 받아들이면 안정감이 생깁니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_묘_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '얽힘을 피하기 위해 일과 관계를 단순하게 유지하세요',
            '만성 스트레스를 매일 풀어내세요',
            '인내심으로 기준 안에서 실력을 쌓으세요',
          ],
          closing: '끈질긴 제약을 인내로 넘기면, 그 인내가 당신의 가장 단단한 기반이 됩니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 무_진: 봄, 토(비견·겁재) ──
    {
      month_pattern_id: '무_진', day_master: '무', month_branch: '진',
      season: '봄',
      element_interaction: '비견·겁재 (토 × 토) — 같은 흙이 겹쳐 답답함, 저장과 경쟁',
      label: '무토 × 진월 — 산 위에 또 흙이 쌓이는 달, 묵직한 경쟁 속에서 기반이 넓어진다',
      modules: [
        { module_id: '무_진_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '같은 흙이 겹쳐 묵직함과 답답함이 피어납니다 — 조급해하지 마세요',
            '경쟁이 눈에 보이지만, 같은 길을 가는 사람이지 적이 아닙니다',
            '진토의 저장 기운을 활용해 기초를 넓히는 데 집중하세요',
            '버티는 힘을 자산 키우기로 쓰세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_진_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '습한 흙이 겹쳐 비위가 무거워지기 쉽습니다 — 가벼운 식사가 좋습니다',
            '체중 관리에 유의하세요 — 무게가 실리는 시기입니다',
            '관절, 피부에 습기가 영향을 줄 수 있으니 건조하게 유지하세요',
            '가볍게 몸을 움직이는 것이 소화에 도움이 됩니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_진_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '같은 분야의 경쟁자가 가까이 있습니다 — 협력하면 두 배로 자랍니다',
            '기초를 다지고 자산을 모으는 데 유리한 시기입니다',
            '자기 자리를 확실히 세우는 것이 경쟁에서 유리한 전략입니다',
            '꾸준함과 묵묵함이 인정으로 이어집니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_진_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '나와 비슷한 성향의 인연이 다가올 수 있습니다',
            '관계에서 주도권을 다투면 둘 다 답답해집니다 — 함께하는 것을 목표로',
            '신뢰를 바탕으로 공동의 기반을 쌓는 시기입니다',
            '경쟁심이 관계를 긁지 않도록 주의하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_진_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '저축과 저장에 가장 유리한 시기입니다 — 진토의 창고 기운을 활용하세요',
            '경쟁으로 인한 지출이 늘 수 있으니 예산을 세우세요',
            '장기적으로 가치가 오르는 것에 투자하세요',
            '같은 기운끼리 돈 문제로 갈등이 생기기 쉬우니 미리 명확히 합의하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_진_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '같은 기운의 사람들이 몰려드는 시기입니다 — 인맥이 넓어집니다',
            '겸손하지 않으면 기싸움이 시작됩니다 — 한 발 물러서세요',
            '비슷한 사람과 협력하면 시너지가 납니다',
            '고집이 강해지면 가까운 사람부터 멀어집니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_진_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '기초를 넓히고 자산을 축적하는 시기입니다',
            '배우고 쌓아둔 것이 진토에 저장되어 나중에 큰 힘이 됩니다',
            '서두르지 말고 기반을 단단히 하는 데 시간을 쓰세요',
            '경쟁 속에서 협력하는 법을 배우는 것이 이 시기의 과제입니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_진_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '저축과 기초 확장에 집중하세요',
            '경쟁자와 협력하는 자세를 가지세요',
            '조급함을 내려놓고 기반을 다지세요',
          ],
          closing: '쌓아둔 기반이 훗날 가장 든든한 자산이 됩니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 무_사: 여름, 화생토(생) ──
    {
      month_pattern_id: '무_사', day_master: '무', month_branch: '사',
      season: '여름',
      element_interaction: '생 (화생토) — 초여름의 온화한 불이 산을 따뜻하게 데움, 흙이 자람',
      label: '무토 × 사월 — 따뜻한 온기가 산을 데우는 달, 배움과 지원으로 성장이 빠르다',
      modules: [
        { module_id: '무_사_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '따뜻한 지원이 밀려옵니다 — 받아들이는 것을 주저하지 마세요',
            '배움의 기회가 가까이 있습니다 — 열린 마음으로 맞이하세요',
            '서두르지 않아도 자연스럽게 자라는 시기입니다',
            '받은 따뜻함을 내 것으로 소화하는 데 집중하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_사_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '따뜻한 기운이 체력을 지원합니다 — 전반적으로 양호합니다',
            '너무 뜨거워지면 건조해질 수 있으니 수분 섭취를 잊지 마세요',
            '가벼운 산책, 요가 등 부드러운 운동이 잘 맞습니다',
            '온기가 좋지만 과도한 활동은 피하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_사_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '배움과 지원이 일에 도움이 되는 시기입니다',
            '문서, 인가, 교육 등 종이 위에서 완성되는 일에 유리합니다',
            '멘토나 지도자를 만나면 성장이 빨라집니다',
            '차분하게 실력을 증명하면 인정이 따라옵니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_사_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '따뜻하고 배려 있는 인연이 다가올 수 있습니다',
            '포근하고 안정적인 관계로 발전하기 좋은 시기입니다',
            '서로를 지원하는 관계가 가장 아름다운 시기입니다',
            '천천히 깊이를 더하는 것이 관계를 단단하게 만듭니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_사_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '안정적인 흐름이 예상됩니다 — 큰 변동보다 점진적 성장',
            '보존과 관리에 집중하는 것이 유리합니다',
            '문서로 확정되는 재물 — 예금, 적립 등이 좋습니다',
            '모험보다 관리가 재물을 키웁니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_사_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '윗사람과의 관계가 원만합니다 — 인정과 지원을 받을 수 있습니다',
            '따뜻한 인간관계가 자연스럽게 형성되는 시기입니다',
            '받은 따뜻함을 주변에 나누면 더 크게 돌아옵니다',
            '신뢰를 바탕으로 한 깊은 관계를 맺기 좋습니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_사_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '배움의 황금기입니다 — 새로운 것을 배우기에 가장 좋은 시기',
            '지원을 받아들여 성장의 속도를 높이세요',
            '따뜻한 온기 속에서 자신감이 자라납니다',
            '배운 것을 정리하고 내 것으로 만드는 데 시간을 쓰세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_사_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '배움의 기회를 놓치지 마세요',
            '따뜻한 지원을 받아들이세요',
            '건조함을 경계하며 수분과 휴식을 챙기세요',
          ],
          closing: '받아들인 배움이 자연스럽게 실력으로 굳어지는 시기입니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 무_오: 여름, 화생토(생) ──
    {
      month_pattern_id: '무_오', day_master: '무', month_branch: '오',
      season: '여름',
      element_interaction: '생 (화생토) — 한여름의 맹렬한 불이 산을 달굼, 에너지 과다',
      label: '무토 × 오월 — 한여름의 뜨거운 불이 산을 달구는 달, 열정의 온도를 조절해야 한다',
      modules: [
        { module_id: '무_오_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '에너지가 넘치지만, 너무 뜨거우면 조급해집니다 — 열기를 식히세요',
            '완벽을 추구하다 스스로를 옥죌 수 있습니다 — 적당히 놓아주세요',
            '열정은 좋지만, 집착이 되면 답답해집니다',
            '멈출 줄 아는 것이 진짜 강한 사람입니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_오_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '한여름의 열기가 몸에 무리를 줄 수 있습니다 — 수면과 수분이 필수',
            '심장, 혈액 순환에 주의하세요 — 열이 올라가기 쉽습니다',
            '수영, 물가 산책 등 물 가까이에서 열을 식히는 것이 좋습니다',
            '매운 음식, 술은 열기를 더하니 줄이세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_오_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '에너지가 넘쳐 일을 밀어붙일 수 있습니다 — 그러나 휴식도 필요합니다',
            '성과가 보이는 시기이지만, 너무 무리하면 뒤가 흐트러집니다',
            '열정을 방향으로 집중시키세요 — 흩어지면 소비만 됩니다',
            '속도 조절이 일의 질을 좌우합니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_오_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '열정적인 인연이 다가올 수 있습니다 — 그러나 너무 뜨거우면 금방 식습니다',
            '감정의 온도를 조절하세요 — 끓어오르는 만큼 식는 것도 빠릅니다',
            '안정감 있는 관계로 발전시키려면 속도를 늦추세요',
            '감정이 격해지면 한 발 물러서서 숨을 고르세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_오_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '재물의 흐름이 활발합니다 — 그러나 들어오는 만큼 나가기도 쉽습니다',
            '열정적인 투자는 위험합니다 — 차분하게 점검하세요',
            '식히고 정리하는 시간이 재물을 지킵니다',
            '조급한 판단은 후회로 돌아옵니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_오_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '열정적으로 사람을 대하다 지칠 수 있습니다 — 에너지 분배를 잘하세요',
            '감정이 격해지기 쉬우니 말실수를 조심하세요',
            '받은 만큼 주는 관계가 지속 가능합니다',
            '화가 차오르면 한 발 물러서세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_오_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '에너지가 넘쳐 배움의 속도가 빠릅니다 — 그러나 소화할 시간도 필요',
            '뜨거운 열정을 지속 가능한 열의로 바꾸세요',
            '멈추고 정리하는 시간이 성장의 질을 높입니다',
            '한 번에 너무 많이 배우려 하지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_오_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '열기를 식히고 휴식을 챙기세요',
            '열정을 한 방향으로 집중시키세요',
            '감정의 온도를 조절하세요',
          ],
          closing: '열정을 지속 가능한 열의로 다스리는 사람이 가장 멀리 갑니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 무_미: 여름, 토(비견·겁재) ──
    {
      month_pattern_id: '무_미', day_master: '무', month_branch: '미',
      season: '여름',
      element_interaction: '비견·겁재 (토 × 토) — 건조한 흙이 겹쳐 조급함과 경쟁이 치열',
      label: '무토 × 미월 — 건조한 흙이 산에 겹치는 달, 경쟁과 조급함 속에서 인내가 무기',
      modules: [
        { module_id: '무_미_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '같은 흙이 겹치되 건조합니다 — 조급함과 경쟁심이 강해집니다',
            '답답함을 느끼기 쉬운 시기입니다 — 한 발 물러서서 보세요',
            '건조한 흙은 갈라지기 쉽습니다 — 마음의 균열을 조심하세요',
            '인내심이 가장 강한 무기입니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_미_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '건조한 흙이 위장에 부담을 줍니다 — 충분한 수분과 유분 섭취',
            '열기가 남아 있으니 과로하면 쉽게 지칩니다',
            '스트레스로 인한 위염, 장 문제를 조심하세요',
            '차가운 음식으로 열기를 식히되, 너무 차게는 마시지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_미_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '경쟁이 치열한 환경에 놓일 수 있습니다 — 성실함이 무기입니다',
            '조급하게 결과를 내려 하지 말고 과정에 집중하세요',
            '같은 분야 사람과의 마찰이 잦습니다 — 양보가 전략입니다',
            '기초를 지키는 것이 앞서가는 것보다 납니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_미_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '관계에서 답답함을 느끼기 쉽습니다 — 서로의 공간을 존중하세요',
            '경쟁심이 애정을 그르칠 수 있습니다 — 비교하지 마세요',
            '차분하게 서로를 알아가는 시간이 필요합니다',
            '건조한 시기이니 관계에 의식적으로 온기를 더하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_미_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '경쟁으로 인한 지출이 늘어나기 쉽습니다 — 예산 관리가 필수',
            '체면이나 경쟁심으로 사는 것은 후회로 돌아옵니다',
            '저축은 습관으로, 지출은 계획으로 관리하세요',
            '조급한 투자는 위험합니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_미_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '같은 기운의 사람과 마찰이 잦습니다 — 한 발 물러서세요',
            '조급함이 관계를 긁습니다 — 여유를 가지세요',
            '비교와 경쟁을 내려놓으면 관계가 편안해집니다',
            '건조한 시기이니 관계에 물(유연함)을 더하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_미_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '조급함을 경계하고 묵묵히 기다리는 연습이 필요합니다',
            '건조한 시기에는 무리한 성장보다 유지가 중요합니다',
            '인내심이 가장 큰 성장의 열매를 가져옵니다',
            '비교 대신 자기 몫에 집중하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_미_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '조급함을 내려놓고 과정에 집중하세요',
            '수분과 휴식으로 건조함을 보충하세요',
            '경쟁에서 한 발 물러서세요',
          ],
          closing: '조급함을 이기는 인내가 가장 단단한 경쟁력이 됩니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 무_신: 가을, 토생금(생) ──
    {
      month_pattern_id: '무_신', day_master: '무', month_branch: '신',
      season: '가을',
      element_interaction: '생 (토생금) — 산이 큰 쇠를 품고 길러냄, 흙이 소모됨',
      label: '무토 × 신월 — 산이 쇠를 품어 길러내는 달, 결과물을 내며 에너지를 소모한다',
      modules: [
        { module_id: '무_신_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '품고 기르던 것을 밖으로 내보내는 시기입니다 — 적극적으로 표현하세요',
            '흙이 쇠를 길러내며 에너지를 소모합니다 — 무리하지 마세요',
            '산출의 기쁨이 있지만, 그만큼 체력이 빠집니다 — 균형을 잡으세요',
            '내보내는 만큼 보충하는 것을 잊지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_신_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '토가 금을 생하며 기운이 빠집니다 — 피로감을 느끼기 쉽습니다',
            '호흡기, 폐, 대장 건강에 주의하세요 — 금 기운과 연결됩니다',
            '규칙적인 식사와 충분한 휴식이 체력을 지켜줍니다',
            '피로가 누적되면 면역력이 떨어지니 미리 관리하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_신_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '결과물을 내고 표현하는 데 유리한 시기입니다',
            '지금까지 쌓은 것을 세상에 보여주세요 — 식신의 힘이 돕습니다',
            '한 번에 너무 많이 내보내면 고갈합니다 — 속도 조절이 중요합니다',
            '기술, 전문성, 경험에서 재물을 찾기 좋습니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_신_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '자기를 표현하면 매력이 빛을 발하는 시기입니다',
            '솔직하게 마음을 드러내세요 — 표현의 에너지가 돕습니다',
            '너무 적극적으로 나가면 상대가 부담할 수 있습니다 — 속도를 조절하세요',
            '결과보다 관계 자체를 가꾸는 데도 신경 쓰세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_신_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '활동의 결과로 재물이 들어올 수 있는 시기입니다',
            '들어오는 만큼 체력이 빠지니 — 무리하지 마세요',
            '기술, 장인정신, 전문성에서 재물을 찾으세요',
            '수확의 일부를 다음 씨앗으로 남겨두세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_신_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '주변에 에너지를 주는 시기입니다 — 그러나 자신의 한계를 아세요',
            '표현이 많아지니 말의 무게를 조심하세요',
            '주는 것과 받는 것의 균형이 건강한 관계를 만듭니다',
            '너무 많이 베풀면 고갈합니다 — 자신도 챙기세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_신_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '배운 것을 밖으로 표현하며 완성하는 시기입니다',
            '결과물을 만들어내는 과정에서 가장 많이 배웁니다',
            '소모를 인정하고 충분히 보충하는 것이 지속 가능한 성장입니다',
            '쌓아둔 것을 정리하며 다음 단계를 구상하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_신_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '쌓아둔 것을 적극적으로 표현하고 내보내세요',
            '체력 소모를 인정하고 충분히 보충하세요',
            '결과물의 질에 집중하세요',
          ],
          closing: '품었던 것을 세상에 내보내는 만큼, 그 자리를 다시 채우는 것이 과제입니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 무_유: 가을, 토생금(생) ──
    {
      month_pattern_id: '무_유', day_master: '무', month_branch: '유',
      season: '가을',
      element_interaction: '생 (토생금) — 산이 정제된 쇠를 배출함, 섬세한 결실과 체력 소모',
      label: '무토 × 유월 — 산이 정제된 쇠를 배출하는 달, 섬세한 완성의 피로 속에서 결실을 맺는다',
      modules: [
        { module_id: '무_유_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '섬세하게 다듬어 결과물을 완성하는 시기입니다',
            '완벽을 추구하되, 지나치면 스스로를 옥죕니다 — 적당히 놓아주세요',
            '흙이 정제된 쇠를 배출하며 에너지가 빠집니다 — 휴식을 잊지 마세요',
            '결과물에 대한 집착에서 벗어나 과정을 인정하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_유_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '금 기운이 강해져 피로가 누적됩니다 — 수면이 최우선입니다',
            '호흡기, 피부 건조를 조심하세요',
            '명상, 독서, 산책 등 정제된 활동이 마음을 편안하게 합니다',
            '섬세한 작업의 눈 피로, 어깨 긴장을 풀어주세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_유_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '결과물의 질이 빛을 발하는 시기입니다 — 섬세함이 무기입니다',
            '다듬고 완성하는 작업에 유리합니다 — 마무리에 집중하세요',
            '비판적인 눈이 강해지니, 자신과 타인에게 너무 엄격하지 마세요',
            '시작보다 완성에 에너지를 쓰세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_유_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '섬세하고 감각적인 인연이 다가올 수 있습니다',
            '완벽한 상대를 찾기보다, 함께 다듬어가는 관계를 만드세요',
            '비판적인 말투가 상처가 될 수 있습니다 — 부드럽게 표현하세요',
            '상대의 장점을 먼저 보는 눈을 기르세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_유_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '다듬어 만든 결과물에서 재물이 생길 수 있는 시기입니다',
            '섬세한 계획과 관리가 재물을 지킵니다',
            '충동적 지출보다 정교한 관리가 유리합니다',
            '완성도가 높은 일일수록 가치를 인정받습니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_유_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '예리한 관찰력이 생기지만, 너무 날카로우면 관계가 상합니다',
            '비판보다 격려를 먼저 하세요',
            '섬세한 배려가 깊은 관계를 만듭니다',
            '상대의 결점을 지적하기보다 장점을 끌어올리세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_유_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '다듬고 완성하는 과정에서 큰 성장이 있습니다',
            '비판적 사고를 건설적으로 쓰세요 — 흠을 찾기보다 개선을 찾으세요',
            '완성의 기쁨이 다음 시작의 원동력이 됩니다',
            '섬세함을 기르되, 집착에서는 벗어나세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_유_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '다듬고 마무리하는 데 집중하세요',
            '비판을 건설적으로 바꾸세요',
            '피로를 인정하고 충분히 쉬세요',
          ],
          closing: '섬세한 완성의 피로를 견디어 낸 결실이 가장 오래 빛납니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 무_술: 가을, 토(비견·겁재) ──
    {
      month_pattern_id: '무_술', day_master: '무', month_branch: '술',
      season: '가을',
      element_interaction: '비견·겁재 (토 × 토) — 건조하고 단단한 흙이 겹쳐 고집이 세짐',
      label: '무토 × 술월 — 건조한 흙이 산에 겹치는 달, 마무리와 저장 속에서 유연함을 잃지 않아야 한다',
      modules: [
        { module_id: '무_술_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '건조하고 단단한 흙이 겹칩니다 — 고집이 세지고 답답해집니다',
            '닫힌 마음을 열어야 새로운 것이 들어옵니다',
            '마무리와 정리에 집중하되, 완고해지지 마세요',
            '묵은 것을 내려놓아야 새것이 들어올 자리가 생깁니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_술_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '건조한 흙이 위장을 긁습니다 — 유분과 수분을 충분히',
            '변비, 피부 건조를 조심하세요',
            '스트레스가 닫힌 채로 쌓이기 쉽습니다 — 의식적으로 풀어내세요',
            '따뜻하고 부드러운 음식이 위장에 좋습니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_술_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '기존의 일을 정리하고 마무리하는 데 유리합니다',
            '고집이 세지니, 다른 사람의 의견에 귀를 기울이세요',
            '저장과 보존의 시기 — 새로 시작하기보다 다듬는 것이 유리합니다',
            '완고한 태도가 협력의 기회를 막지 않도록 주의하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_술_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '관계에서 완고해지기 쉬운 시기입니다 — 유연하게 다가가세요',
            '답답함을 느끼면 혼자만의 시간이 필요합니다 — 그것을 인정하세요',
            '과거의 인연이나 오래된 관계를 정리하는 시기이기도 합니다',
            '상대를 바꾸려 하지 말고, 내 유연함을 먼저 늘리세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_술_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '저장과 보존에 유리한 시기입니다 — 저축이 잘 됩니다',
            '인색해지면 관계가 상합니다 — 균형이 필요합니다',
            '문서, 부동산 등 확실한 형태의 재물이 유리합니다',
            '지출을 최소화하고 비상금을 확보하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_술_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '고집이 세져 주변과 마찰이 생길 수 있습니다 — 한 발 물러서세요',
            '내 방식만 옳다는 생각을 경계하세요',
            '오래된 관계를 돌아보고 감사를 표현하세요',
            '완고한 태도를 부드럽게 풀어야 관계가 지속됩니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_술_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '정리와 마무리를 통해 내공이 깊어지는 시기입니다',
            '고집을 인정하고 유연함을 기르는 것이 과제입니다',
            '닫힌 것을 여는 연습이 가장 큰 성장입니다',
            '묵은 것을 비우면 새것이 들어올 공간이 생깁니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_술_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '완고함을 경계하고 유연해지세요',
            '정리와 마무리에 집중하세요',
            '건조함을 보충하고 스트레스를 풀어내세요',
          ],
          closing: '고집을 부드럽게 풀고 묵은 것을 비우는 사람이 다음 문을 엽니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 무_해: 겨울, 토극수(극) ──
    {
      month_pattern_id: '무_해', day_master: '무', month_branch: '해',
      season: '겨울',
      element_interaction: '극 (토극수) — 산이 큰 물을 막으나 무너질 수 있음, 위태로움',
      label: '무토 × 해월 — 산이 큰 물을 막아서는 달, 욕심을 부리면 무너지는 위태로운 균형',
      modules: [
        { module_id: '무_해_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '물(재물, 변화)의 흐름이 강해집니다 — 욕심을 부리면 무너집니다',
            '물을 막으려 하지 말고, 물의 흐름을 다스리는 지혜가 필요합니다',
            '변화와 이동이 많은 시기입니다 — 중심을 잃지 마세요',
            '버티는 힘은 좋지만, 버티는 방향이 옳은지 점검하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_해_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '차가운 물 기운이 몸을 식힙니다 — 따뜻하게 유지하세요',
            '신장, 방광, 비뇨기 건강에 주의하세요',
            '과로와 수면 부족이 면역력을 떨어뜨립니다 — 충분히 쉬세요',
            '따뜻한 온천, 찜질로 몸을 데우세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_해_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '변화와 이동이 많은 시기입니다 — 계획 없는 움직임은 피하세요',
            '재물과 관련된 기회가 눈앞에 있어도, 신중하게 접근하세요',
            '흔들리지 않고 중심을 잡는 것이 가장 중요합니다',
            '한 번에 큰 것을 노리지 말고 단계적으로 접근하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_해_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '강렬하고 변화가 많은 인연이 다가올 수 있습니다',
            '감정의 파도가 큽니다 — 흔들리지 않게 자기 중심을 잡으세요',
            '관계가 빠르게 발전했다가 변할 수 있습니다 — 속도를 조절하세요',
            '감정의 흐름을 억누르지 말고 건강하게 표현하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_해_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '재물의 흐름이 큽니다 — 들어올 자리도, 나갈 자리도 큽니다',
            '욕심을 부리면 산이 무너집니다 — 한 번에 큰 것을 노리지 마세요',
            '보존이 우선입니다 — 위험한 투자, 큰 돈거래는 절대 피하세요',
            '재물의 흐름을 다스리되, 흐름에 휩쓸리지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_해_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '인연의 드나듬이 많은 시기입니다 — 가변적인 관계에 휩쓸리지 마세요',
            '물처럼 흐르는 관계에 너무 매달리지 마세요',
            '확실한 사람을 구별하는 안목이 필요합니다',
            '변화 속에서 변하지 않는 관계를 소중히 하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_해_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '변화 속에서 중심을 잡는 연습이 가장 큰 성장입니다',
            '물의 흐름을 읽는 눈을 기르세요 — 억지로 막지 말고 흐름을 다스리세요',
            '겨울의 에너지를 비축에 쓰세요 — 무리한 성장은 위험합니다',
            '변화를 두려워하지 말고 대비하는 지혜를 기르세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_해_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '중심을 잃지 않고 버티세요',
            '재물의 욕심을 경계하세요',
            '따뜻하게 유지하고 충분히 쉬세요',
          ],
          closing: '물의 흐름을 억지로 막지 않고 다스리는 사람이 산을 지킵니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 무_자: 겨울, 토극수(극) ──
    {
      month_pattern_id: '무_자', day_master: '무', month_branch: '자',
      season: '겨울',
      element_interaction: '극 (토극수) — 차갑고 깊은 물이 흙을 서서히 적심, 불안정',
      label: '무토 × 자월 — 깊고 차가운 물이 산을 적시는 달, 겉은 잔잔하지만 속은 흔들린다',
      modules: [
        { module_id: '무_자_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '차가운 물이 서서히 흙을 적십니다 — 겉보기엔 잔잔하지만 속은 흔들립니다',
            '안정감을 잃기 쉬운 시기입니다 — 내 중심을 단단히 하세요',
            '불안을 인정하되, 불안에 휩쓸리지 마세요',
            '잔잔한 겉모습에 속아 방심하지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_자_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '차가운 기운이 뼈까지 스며듭니다 — 몸을 따뜻하게 유지하세요',
            '신장, 방광, 혈액 순환에 주의하세요',
            '수면 부족이 면역력을 무너뜨립니다 — 규칙적인 수면이 필수입니다',
            '따뜻한 음식과 음료로 안에서부터 데우세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_자_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '일의 흐름이 느리고 차분합니다 — 서두르지 마세요',
            '안정적인 기반 위에서 일하는 것이 중요합니다',
            '겉으로는 평온해도 속으로는 변화가 진행 중입니다 — 세심한 관찰이 필요합니다',
            '확실한 기반 위에서 움직이세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_자_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '차분하고 깊은 인연이 다가올 수 있습니다 — 겉모습보다 깊이를 보세요',
            '감정이 겉으로 잘 드러나지 않는 시기입니다 — 솔직하게 표현하세요',
            '관계의 기반을 다지는 시기입니다 — 서두르지 말고 신뢰를 쌓으세요',
            '차가운 시기이니 의식적으로 따뜻하게 다가가세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_자_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '재물의 흐름이 잔잔하지만 확실합니다 — 안정적인 관리가 유리합니다',
            '차가운 시기에는 보존이 우선입니다 — 무리한 투자는 피하세요',
            '작지만 확실한 수입원을 관리하세요',
            '들어오는 재물을 차곡차곡 쌓으세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_자_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '관계가 차분해지지만, 소통이 줄어들 수 있습니다 — 의식적으로 연락하세요',
            '겉으로 드러나지 않는 감정을 살피세요',
            '깊은 관계일수록 말하지 않아도 알아주는 시기입니다',
            '차가운 시기이니 따뜻한 말 한마디가 큰 힘이 됩니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_자_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '차분하게 내면을 다지는 시기입니다 — 겉으로의 성장보다 내공이 중요합니다',
            '불안을 다스리는 연습이 가장 큰 성장입니다',
            '겨울의 에너지로 뿌리를 깊이 내리세요',
            '잔잔함 속에서 흔들리는 것을 관찰하는 눈을 기르세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_자_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '몸과 마음을 따뜻하게 유지하세요',
            '안정감을 잃지 않도록 중심을 잡으세요',
            '내면의 뿌리를 깊이 내리세요',
          ],
          closing: '잔잔한 겉모습 뒤의 흔들림을 아는 사람이 진짜 안정을 만듭니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 무_축: 겨울, 토(비견·겁재) ──
    {
      month_pattern_id: '무_축', day_master: '무', month_branch: '축',
      season: '겨울',
      element_interaction: '비견·겁재 (토 × 토) — 얼어붙은 흙이 겹쳐 정체됨, 인내와 잠복',
      label: '무토 × 축월 — 산이 한겨울에 얼어붙는 달, 정체 속에서 인내로 봄을 준비한다',
      modules: [
        { module_id: '무_축_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '흙이 얼어붙어 정체된 시기입니다 — 인내가 가장 중요합니다',
            '겉보기엔 멈춰 있지만, 속에서는 씨앗이 잠복하고 있습니다',
            '조급해하지 말고 때를 기다리세요',
            '버티는 힘을 비축에 쓰세요 — 지금은 쌓을 때입니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_축_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '차갑고 굳은 흙이 위장 기능을 떨어뜨립니다 — 따뜻한 음식이 필수입니다',
            '관절 뻣뻣함, 혈액 순환 부족을 조심하세요',
            '따뜻한 온천, 찜질 등 온기로 몸을 데우세요',
            '찬 음식, 생것은 피하고 따뜻하게 조리된 음식을 드세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_축_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '진전이 더딘 시기입니다 — 서두르지 말고 기반을 다지세요',
            '인내와 묵묵한 노력이 나중에 빛을 발합니다',
            '새로운 시작보다 기존 일을 충실히 하는 것이 유리합니다',
            '지금 쌓는 기반이 봄의 도약이 됩니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_축_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '관계가 차분하고 정적인 시기입니다 — 서두르지 마세요',
            '감정 표현이 줄어들 수 있습니다 — 의식적으로 따뜻하게 다가가세요',
            '깊은 신뢰를 쌓는 시기입니다 — 시간이 관계를 완성합니다',
            '차가운 시기일수록 작은 따뜻함이 크게 느껴집니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_축_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '저장과 보존에 가장 유리한 시기입니다 — 저축이 잘 됩니다',
            '지출을 최소화하고 비상금을 확보하세요',
            '얼어붙은 시기에는 움직이는 것보다 지키는 것이 유리합니다',
            '확실하고 안정적인 형태로 재물을 묶어두세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_축_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '관계가 차분해지고 왕래가 줄어드는 시기입니다',
            '가까운 사람과 따뜻한 시간을 보내세요',
            '묵묵히 곁에 있는 사람의 소중함을 깨닫는 시기입니다',
            '적지만 깊은 관계에 에너지를 집중하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_축_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '겉으로의 성장이 더딘 시기입니다 — 내면의 뿌리가 깊어집니다',
            '인내를 기르는 것이 가장 큰 성장입니다',
            '얼어붙은 땅 아래에서 씨앗이 자라고 있습니다 — 봄을 준비하세요',
            '조용히 배우고 정리하는 시간이 내공을 쌓습니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '무_축_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '인내를 가지고 기반을 다지세요',
            '몸을 따뜻하게 유지하세요',
            '봄을 위해 에너지를 비축하세요',
          ],
          closing: '한겨울의 인내가 봄의 가장 튼튼한 싹을 틔웁니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ══════════════════════════════════════════════════════════════════
    // 기토(己) — 밭, 비옥한 흙 (음토) × 12월지
    // 이미지: 품고 기르고 배려하는 힘, 포용력, 실용성. 걱정 · 잡생각 주의.
    // ══════════════════════════════════════════════════════════════════

    // ── 기_인: 봄, 목극토(극) ──
    {
      month_pattern_id: '기_인', day_master: '기', month_branch: '인',
      season: '봄',
      element_interaction: '극 (목극토) — 큰 나무가 밭에 깊이 뿌리를 내림, 밭이 크게 흔들림',
      label: '기토 × 인월 — 큰 나무가 밭에 뿌리를 내리는 달, 압박 속에서 포용의 힘을 시험받는다',
      modules: [
        { module_id: '기_인_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '밭에 큰 나무가 뿌리를 내리면 밭 전체가 흔들립니다 — 압박이 큽니다',
            '버티는 힘보다, 품고 조율하는 힘이 필요한 시기입니다',
            '걱정이 많아지기 쉬우니 — 한 가지씩 정리하며 마음을 관리하세요',
            '압박을 품으로써 성장하는 밭의 특성을 믿으세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_인_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '나무 뿌리가 밭을 뒤흔들면 소화기가 가장 먼저 흔들립니다',
            '걱정과 불안이 위장을 긁습니다 — 마음의 안정이 건강의 열쇠입니다',
            '가벼운 산책, 따뜻한 차로 마음과 몸을 함께 데우세요',
            '불안이 수면을 방해할 수 있으니 잠들기 전 마음을 비우세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_인_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '책임이나 권한이 주어지면 걱정이 커집니다 — 하지만 실력으로 증명하세요',
            '밭은 씨앗을 품듯, 새로운 역할을 품으며 성장합니다',
            '작은 일부터 차곡차곡 쌓아 신뢰를 만드세요',
            '포용력을 발휘하되, 자기 몫을 놓치지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_인_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '책임감 강한 인연이 다가올 수 있습니다 — 하지만 상대의 기준이 부담일 수 있습니다',
            '관계에서 기대는 힘이 큽니다 — 서로의 공간을 존중하세요',
            '걱정을 솔직히 나누면 관계가 깊어집니다',
            '상대를 품되, 자신이 흔들리지 않도록 중심을 잡으세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_인_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '압박 속에서 재물을 관리하는 것이 과제입니다 — 걱정하되 행동으로 옮기세요',
            '실용적인 관리가 재물을 지킵니다',
            '복잡한 투자보다 단순하고 확실한 방식을 선택하세요',
            '작은 것부터 차곡차곡 쌓는 것이 안전합니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_인_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '사람의 기대에 휘둘리기 쉬운 시기입니다 — 경계를 부드럽게 세우세요',
            '모두를 다 품으려 하면 지칩니다 — 자신의 한계를 인정하세요',
            '부드럽지만 단호한 태도가 관계를 지킵니다',
            '품는 것과 거절하는 것의 균형을 기르세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_인_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '압박을 포용의 힘으로 바꾸는 것이 성장입니다',
            '걱정을 행동으로 바꾸는 연습을 하세요',
            '씨앗을 품듯 새로운 것을 배우며 자라세요',
            '품는 힘을 키우되, 자기 돌봄도 잊지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_인_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '걱정을 한 가지씩 정리하고 행동으로 옮기세요',
            '압박을 실용적으로 관리하세요',
            '마음과 몸을 따뜻하게 유지하세요',
          ],
          closing: '압박을 품어내는 포용력이 밭의 가장 큰 힘입니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 기_묘: 봄, 목극토(극) ──
    {
      month_pattern_id: '기_묘', day_master: '기', month_branch: '묘',
      season: '봄',
      element_interaction: '극 (목극토) — 덩굴과 잡초가 밭에 엉킴, 질기고 풀기 어려운 얽힘',
      label: '기토 × 묘월 — 덩굴이 밭에 엉키는 달, 얽힘을 억지로 풀면 더 엉킨다',
      modules: [
        { module_id: '기_묘_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '덩굴이 밭에 엉키듯 관계와 일이 얽힙니다 — 억지로 풀면 더 엉킵니다',
            '하나씩 차분하게 푸는 지혜가 필요합니다',
            '잡생각이 덩굴처럼 자라니 — 마음의 잡초를 의식적으로 제거하세요',
            '얽힘을 인정하면 차분하게 대응할 수 있습니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_묘_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '얽힘과 스트레스가 소화기를 뒤흔듭니다 — 위장, 장이 예민해집니다',
            '불안이 수면을 방해할 수 있습니다 — 잠들기 전 마음을 비우세요',
            '가벼운 스트레칭, 명상으로 몸의 긴장을 풀어주세요',
            '복잡한 감정이 몸에 쌓이지 않도록 풀어내는 시간이 필요합니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_묘_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '일이 얽히고 꼬일 수 있습니다 — 서두르면 더 복잡해집니다',
            '차분하게 상황을 정리하고 우선순위를 매기세요',
            '인내심 있게 기다리면 얽힘이 풀리기 시작합니다',
            '한 번에 모든 것을 해결하려 하지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_묘_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '관계가 얽히기 쉬운 시기입니다 — 복잡한 감정이 엉킵니다',
            '서두르지 말고 한 가닥씩 감정을 정리하세요',
            '오해가 쌓이지 않도록 대화하세요 — 침묵은 얽힘을 키웁니다',
            '감정의 실타래를 하나씩 풀어가는 인내가 필요합니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_묘_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '재물 문제가 얽힐 수 있습니다 — 복잡한 거래는 피하세요',
            '단순하고 깔끔한 재물 관리가 안전합니다',
            '공동 계좌, 동업 등은 명확히 합의하세요',
            '얽힌 재물 문제는 서두르지 말고 하나씩 푸세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_묘_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '인간관계가 미묘하게 얽히는 시기입니다 — 직접적으로 부딪히지 마세요',
            '사람의 말 뒤에 숨은 뜻을 살피되, 지나치게 해석하지는 마세요',
            '얽힌 것을 부드럽게 푸는 대화가 필요합니다',
            '관계를 단순하게 유지하면 얽힘이 줄어듭니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_묘_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '얽힘을 푸는 과정에서 인내심과 지혜가 자랍니다',
            '복잡한 것을 단순하게 보는 눈을 기르세요',
            '잡생각을 관리하는 습관이 마음의 밭을 깨끗하게 유지합니다',
            '얽힘에서 배우는 것이 얽힘을 피하는 것보다 많습니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_묘_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '얽힌 문제를 하나씩 차분하게 푸세요',
            '잡생각을 관리하고 마음의 밭을 가꾸세요',
            '복잡한 상황에서 단순함을 유지하세요',
          ],
          closing: '얽힘을 부드럽게 푸는 인내가 밭을 다시 비옥하게 만듭니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 기_진: 봄, 토(비견·겁재) ──
    {
      month_pattern_id: '기_진', day_master: '기', month_branch: '진',
      season: '봄',
      element_interaction: '비견·겁재 (토 × 토) — 비옥한 흙이 밭에 더해짐, 지원과 경쟁',
      label: '기토 × 진월 — 비옥한 흙이 밭에 더해지는 달, 실용적으로 기반을 넓히기 좋다',
      modules: [
        { module_id: '기_진_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '비옥한 흙이 밭에 더해집니다 — 성장의 토대가 넓어집니다',
            '같은 흙이 겹쳐 경쟁도 있지만, 밭은 함께 자라는 것에 익숙합니다',
            '실용적으로 기반을 다지세요 — 지금 쌓는 것이 나중의 수확이 됩니다',
            '경쟁보다 협력에 무게를 두세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_진_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '습한 흙이 비위에 무게를 줍니다 — 가벼운 식사가 좋습니다',
            '체중 관리에 유의하세요',
            '습기를 조심하세요 — 관절, 피부에 습기가 영향을 줄 수 있습니다',
            '소화를 돕는 가벼운 운동이 좋습니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_진_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '기반을 넓히고 자산을 모으는 데 유리합니다',
            '같은 분야 사람과 협력하면 더 큰 결과가 나옵니다',
            '실용적인 계획과 꼼꼼한 실행이 빛을 발합니다',
            '씨앗을 심듯 장기적인 프로젝트에 투자하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_진_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '안정적이고 실용적인 인연이 다가올 수 있습니다',
            '서로의 기반을 함께 다지는 관계가 좋습니다',
            '포용력을 발휘하되, 자신을 잃지 마세요',
            '함께 성장하는 것을 목표로 하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_진_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '저축과 저장에 매우 유리한 시기입니다',
            '실용적인 투자 — 확실한 수익이 있는 것에 집중하세요',
            '경쟁으로 인한 지출을 관리하세요',
            '꼼꼼한 예산 관리가 재물을 키웁니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_진_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '비슷한 성향의 사람과 협력이 잘 됩니다',
            '포용력이 빛을 발하는 시기입니다 — 그러나 한계를 정하세요',
            '받은 만큼 주는 관계가 건강합니다',
            '너무 많이 품으려 하지 말고 자기 몫을 지키세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_진_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '기반을 다지고 씨앗을 뿌리는 시기입니다',
            '실용적인 배움이 가장 잘 맞습니다 — 쓸모있는 것을 배우세요',
            '꾸준함이 수확으로 이어집니다',
            '협력 속에서 배우는 것이 혼자보다 빠릅니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_진_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '실용적으로 기반을 다지세요',
            '같은 분야 사람과 협력하세요',
            '저축과 저장에 집중하세요',
          ],
          closing: '지금 심는 씨앗의 질이 수확의 질을 결정합니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 기_사: 여름, 화생토(생) ──
    {
      month_pattern_id: '기_사', day_master: '기', month_branch: '사',
      season: '여름',
      element_interaction: '생 (화생토) — 따뜻한 햇살이 밭을 데움, 씨앗이 싹트는 시기',
      label: '기토 × 사월 — 따뜻한 햇살이 밭을 데우는 달, 배움과 성장이 가장 빠르다',
      modules: [
        { module_id: '기_사_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '밭에 따뜻한 햇살이 내립니다 — 씨앗이 싹트는 시기입니다',
            '배움과 지원을 받아들이면 성장이 빠릅니다',
            '걱정을 내려놓고 따뜻한 기운을 충분히 흡수하세요',
            '받아들이는 것을 주저하지 마세요 — 밭은 햇살을 품어야 열매를 맺습니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_사_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '따뜻한 기운이 몸을 지원합니다 — 전반적으로 양호한 시기입니다',
            '너무 뜨거워지면 건조해질 수 있으니 수분을 챙기세요',
            '산책, 요가, 가벼운 운동이 밭의 생명력을 높입니다',
            '따뜻한 시기이니 야외 활동이 기운을 끌어올립니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_사_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '배움과 성장의 황금기입니다 — 새로운 것을 배우기에 가장 좋습니다',
            '문서, 교육, 멘토링 등이 일에 큰 도움이 됩니다',
            '따뜻한 인간관계 속에서 일이 잘 풀립니다',
            '배운 것을 바로 써먹을 수 있는 환경을 찾으세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_사_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '따뜻하고 포근한 인연이 다가올 수 있습니다',
            '배려와 포용이 관계를 아름답게 만드는 시기입니다',
            '서로를 키워주는 관계로 발전하기 좋습니다',
            '따뜻함을 나누면 관계가 더 깊어집니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_사_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '안정적이고 점진적인 성장이 예상됩니다',
            '배움에 투자하면 나중에 재물로 돌아옵니다',
            '보존과 관리가 재물을 키웁니다',
            '따뜻한 시기의 수확을 잘 관리하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_사_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '따뜻한 관계가 자연스럽게 형성됩니다',
            '윗사람의 인정과 지원을 받기 좋은 시기입니다',
            '받은 따뜻함을 나누면 더 크게 돌아옵니다',
            '포용력이 관계를 넓히는 시기입니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_사_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '배움의 황금기입니다 — 받아들이는 것을 주저하지 마세요',
            '따뜻한 온기 속에서 자신감이 자라납니다',
            '씨앗이 싹트듯 새로운 가능성이 피어납니다',
            '배운 것을 정리하고 내 것으로 만드세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_사_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '배움의 기회를 놓치지 마세요',
            '따뜻한 기운을 충분히 흡수하세요',
            '걱정을 내려놓고 성장에 집중하세요',
          ],
          closing: '따뜻한 햇살을 흡수한 밭이 가장 풍성한 수확을 낳습니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 기_오: 여름, 화생토(생) ──
    {
      month_pattern_id: '기_오', day_master: '기', month_branch: '오',
      season: '여름',
      element_interaction: '생 (화생토) — 뜨거운 햇볕이 밭을 태움, 메마름과 과도한 열',
      label: '기토 × 오월 — 뜨거운 햇볕이 밭을 태우는 달, 메마름을 경계하고 열기를 식혀야 한다',
      modules: [
        { module_id: '기_오_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '뜨거운 햇볕이 밭을 태웁니다 — 메마름과 조급함을 경계하세요',
            '걱정이 불안으로 타오르기 쉬운 시기입니다 — 마음의 열을 식히세요',
            '너무 많은 것을 한꺼번에 하려 하면 밭이 메마릅니다',
            '열정과 안정의 균형이 필요합니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_오_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '밭이 메마르듯 몸도 건조해집니다 — 수분 섭취가 최우선입니다',
            '심장, 혈액 순환에 열이 올라갈 수 있습니다',
            '물가 산책, 수영 등 차가운 기운으로 열을 식히세요',
            '매운 음식, 술은 열기를 더하니 줄이세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_오_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '에너지가 넘쳐 일을 밀어붙일 수 있습니다 — 그러나 휴식이 필요합니다',
            '너무 열심히 하다 지치면 밭이 황폐해집니다 — 속도를 조절하세요',
            '열정을 한 방향으로 집중시키세요',
            '지속 가능한 속도가 일의 질을 지킵니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_오_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '열정적이지만 불안정한 감정이 피어날 수 있습니다',
            '너무 뜨거운 감정은 빨리 식습니다 — 온도를 조절하세요',
            '안정감 있는 관계로 발전시키려면 속도를 늦추세요',
            '감정이 격해지면 한 발 물러서서 숨을 고르세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_오_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '재물의 흐름이 활발합니다 — 그러나 조급한 판단은 위험합니다',
            '열기에 휩쓸린 투자는 후회로 돌아옵니다',
            '차분하게 점검하고 결정하세요',
            '식히고 정리하는 시간이 재물을 지킵니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_오_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '감정이 격해지기 쉬운 시기입니다 — 말실수를 조심하세요',
            '너무 많은 것을 주려다 지칩니다 — 자신의 한계를 존중하세요',
            '열기를 식히고 차분하게 사람을 대하세요',
            '불안이 관계를 긁지 않도록 주의하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_오_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '열정적인 배움이 가능하지만, 소화할 시간이 필요합니다',
            '열기를 지속 가능한 에너지로 바꾸세요',
            '멈추고 정리하는 시간이 성장의 질을 높입니다',
            '한 번에 너무 많이 배우려 하지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_오_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '열기를 식히고 수분을 충분히 섭취하세요',
            '조급함을 경계하고 속도를 조절하세요',
            '감정의 온도를 관리하세요',
          ],
          closing: '뜨거운 열기를 다스리는 밭이 가장 비옥하게 남습니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 기_미: 여름, 토(비견·겁재) ──
    {
      month_pattern_id: '기_미', day_master: '기', month_branch: '미',
      season: '여름',
      element_interaction: '비견·겁재 (토 × 토) — 같은 흙이 밭에 겹쳐 포용과 답답함이 함께',
      label: '기토 × 미월 — 같은 흙이 밭에 겹치는 달, 포용력과 한계 사이에서 균형을 잡아야 한다',
      modules: [
        { module_id: '기_미_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '같은 흙이 겹쳐 답답함과 걱정이 커집니다',
            '포용하려는 본능이 강해지지만, 너무 많이 품으면 한계에 부딪힙니다',
            '자신의 용량을 아는 것이 중요한 시기입니다',
            '품는 것과 비우는 것의 리듬을 만드세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_미_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '건조하고 무거운 흙이 비위에 부담을 줍니다',
            '걱정이 소화기를 긁습니다 — 마음 관리가 건강 관리입니다',
            '수분 섭취와 가벼운 식사로 위장을 보호하세요',
            '열기가 남아 있으니 과로를 피하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_미_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '같은 분야 사람과 경쟁이 생깁니다 — 실용적으로 대응하세요',
            '너무 많은 일을 떠안지 마세요 — 자신의 역량 안에서 일하세요',
            '포용력이 빛을 발하지만, 한계를 정하는 것도 능력입니다',
            '실용적인 우선순위로 일을 정리하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_미_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '관계에서 답답함을 느끼기 쉽습니다 — 서로의 공간을 존중하세요',
            '너무 많이 배려하다 자신이 지칠 수 있습니다 — 균형이 필요합니다',
            '실용적으로 관계를 관리하세요 — 감정에만 휩쓸리지 마세요',
            '품되 끌려다니지 않는 관계를 만드세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_미_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '경쟁으로 인한 지출을 경계하세요',
            '실용적인 예산 관리가 재물을 지킵니다',
            '체면이나 경쟁심으로 사는 것은 후회로 돌아옵니다',
            '지출을 계획하고 저축을 습관으로 만드세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_미_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '모두를 품으려다 지치는 시기입니다 — 한계를 정하세요',
            '같은 기운의 사람과 답답함을 느낄 수 있습니다 — 거리를 조절하세요',
            '부드럽지만 단호하게 자기 자리를 지키세요',
            '품는 것과 거절하는 것의 균형이 관계를 건강하게 합니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_미_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '자신의 용량을 아는 것이 가장 큰 성장입니다',
            '포용과 한계의 균형을 배우는 시기입니다',
            '답답함을 관리하는 실용적 습관이 필요합니다',
            '비교 대신 자기 몫에 집중하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_미_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '자신의 한계를 정하고 지키세요',
            '걱정과 답답함을 실용적으로 관리하세요',
            '같은 분야 사람과 적절한 거리를 유지하세요',
          ],
          closing: '품는 힘에 한계를 두는 것이 포용력을 오래 유지하는 비결입니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 기_신: 가을, 토생금(생) ──
    {
      month_pattern_id: '기_신', day_master: '기', month_branch: '신',
      season: '가을',
      element_interaction: '생 (토생금) — 밭이 키운 씨앗이 열매를 맺어 나감, 수확과 소모',
      label: '기토 × 신월 — 밭에서 키운 것이 열매로 나가는 달, 수확의 기쁨과 함께 에너지를 소모한다',
      modules: [
        { module_id: '기_신_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '밭에서 키운 것이 열매를 맺어 나갑니다 — 수확의 기쁨이 있는 시기입니다',
            '흙이 쇠를 길러내며 에너지를 소모합니다 — 충분히 보충하세요',
            '결과물을 기쁘게 받아들이되, 다음 씨앗을 준비하세요',
            '수확과 보충의 리듬을 만드세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_신_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '수확의 에너지가 밖으로 나가며 피로가 옵니다 — 휴식이 필수입니다',
            '호흡기, 폐, 대장 건강에 주의하세요',
            '규칙적인 식사로 밭의 영양을 보충하세요',
            '피로가 누적되면 밭의 생명력이 떨어집니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_신_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '결과물을 내고 세상에 보여주기에 좋은 시기입니다',
            '기술, 전문성, 장인정신에서 빛을 발합니다',
            '한 번에 너무 많이 내보내면 밭이 메마릅니다 — 속도를 조절하세요',
            '수확한 결과물의 질을 높이는 데 집중하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_신_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '성과와 매력이 빛을 발하는 시기입니다',
            '자신을 적극적으로 보여주세요 — 수확의 에너지가 돕습니다',
            '결과에만 집중하지 말고 과정의 관계도 가꾸세요',
            '품었던 감정을 솔직하게 표현하기 좋은 시기입니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_신_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '수확의 결과로 재물이 들어올 수 있는 시기입니다',
            '기술과 전문성에서 재물을 찾으세요',
            '들어온 재물의 일부를 다음 씨앗으로 남겨두세요',
            '수확의 기쁨에 휩쓸려 과소비하지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_신_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '주변에 에너지를 주는 시기입니다 — 그러나 자신의 밭도 돌보세요',
            '표현이 많아지니 진정성을 담으세요',
            '주는 것과 받는 것의 균형이 건강한 관계를 만듭니다',
            '품어준 만큼 인정받기 좋은 시기입니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_신_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '키워낸 것을 결과물로 완성하는 시기입니다',
            '수확의 기쁨 속에서 다음을 준비하는 지혜가 필요합니다',
            '소모를 인정하고 충분히 보충하는 것이 지속 가능한 성장입니다',
            '결과물을 내는 과정에서 가장 많이 배웁니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_신_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '결과물을 적극적으로 내보내세요',
            '수확 후 밭의 영양을 보충하세요',
            '다음 씨앗을 준비하세요',
          ],
          closing: '수확의 기쁨을 아는 밭이 다음 씨앗의 가치도 압니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 기_유: 가을, 토생금(생) ──
    {
      month_pattern_id: '기_유', day_master: '기', month_branch: '유',
      season: '가을',
      element_interaction: '생 (토생금) — 밭이 정제된 결실을 내어줌, 섬세한 수확과 피로',
      label: '기토 × 유월 — 밭이 정제된 결실을 내어주는 달, 섬세한 완성 속에서 걱정과 피로를 관리한다',
      modules: [
        { module_id: '기_유_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '섬세하게 다듬은 결과물을 완성하는 시기입니다',
            '완벽을 추구하다 걱정이 커질 수 있습니다 — 적당히 놓아주세요',
            '결과물에 대한 집착이 피로를 부릅니다 — 과정을 인정하세요',
            '섬세함은 장점이지만, 지나치면 불안이 됩니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_유_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '섬세한 작업의 피로가 누적됩니다 — 수면이 최우선입니다',
            '피부 건조, 호흡기 예민함을 조심하세요',
            '명상, 독서, 차 한 잔이 마음을 편안하게 합니다',
            '눈 피로, 어깨 긴장을 의식적으로 풀어주세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_유_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '다듬고 완성하는 작업에 빛을 발합니다 — 섬세함이 무기입니다',
            '마무리와 정리에 집중하세요 — 결과물의 질이 인정받습니다',
            '비판적인 눈이 강해지니 — 자신과 타인에게 너무 엄격하지 마세요',
            '완성도를 높이되, 완벽주의에 갇히지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_유_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '섬세하고 감각적인 인연이 다가올 수 있습니다',
            '완벽한 관계를 찾기보다 함께 다듬어가는 것을 목표로 하세요',
            '비판적인 말투가 상처가 될 수 있습니다 — 부드럽게 표현하세요',
            '상대의 장점을 먼저 보는 눈을 기르세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_유_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '다듬어 만든 결과물에서 재물이 생길 수 있습니다',
            '정교한 관리와 계획이 재물을 지킵니다',
            '섬세하지만 과도한 걱정은 판단을 흐리니 — 차분하게 결정하세요',
            '완성도가 높은 일일수록 가치를 인정받습니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_유_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '예리한 관찰력이 생기지만, 너무 날카로우면 관계가 상합니다',
            '걱정하는 마음을 격려로 바꿔 표현하세요',
            '섬세한 배려가 깊은 관계를 만듭니다',
            '상대의 결점을 지적하기보다 장점을 끌어올리세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_유_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '다듬고 완성하는 과정에서 큰 성장이 있습니다',
            '비판을 건설적으로 쓰세요 — 흠을 찾기보다 개선을 찾으세요',
            '완성의 기쁨이 다음 시작의 씨앗이 됩니다',
            '섬세함을 기르되, 걱정에서는 벗어나세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_유_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '섬세하게 마무리하고 완성하세요',
            '걱정을 건설적인 행동으로 바꾸세요',
            '피로를 인정하고 정제된 휴식을 취하세요',
          ],
          closing: '섬세한 완성의 피로를 견디어 낸 결실이 가장 오래 빛납니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 기_술: 가을, 토(비견·겁재) ──
    {
      month_pattern_id: '기_술', day_master: '기', month_branch: '술',
      season: '가을',
      element_interaction: '비견·겁재 (토 × 토) — 밭이 건조해짐, 정리와 마무리 속에 메마름 주의',
      label: '기토 × 술월 — 밭이 건조해지는 달, 마무리와 정리 속에서 자신을 돌보아야 한다',
      modules: [
        { module_id: '기_술_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '밭이 건조해집니다 — 메마름과 걱정이 커지는 시기입니다',
            '마무리와 정리에 집중하되, 완고해지지 마세요',
            '마른 밭에는 물을 주어야 합니다 — 자신을 챙기는 시간이 필요합니다',
            '묵은 것을 비워야 새것이 들어올 자리가 생깁니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_술_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '건조한 밭이 위장을 긁습니다 — 유분과 수분을 충분히',
            '변비, 피부 건조를 조심하세요',
            '스트레스가 쌓이기 쉬우니 의식적으로 풀어내세요',
            '따뜻하고 부드러운 음식으로 밭에 영양을 주세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_술_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '기존 일을 정리하고 마무리하는 데 유리합니다',
            '고집이 세지니 다른 사람의 의견에 귀를 기울이세요',
            '새로 시작하기보다 다듬고 완성하는 것이 유리합니다',
            '실용적으로 우선순위를 정해 마무리하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_술_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '관계에서 메마름을 느끼기 쉽습니다 — 의식적으로 따뜻하게 다가가세요',
            '완고해지지 말고 유연하게 관계를 가꾸세요',
            '오래된 관계를 정리하거나 돌아보는 시기이기도 합니다',
            '관계에 물(온기)을 주는 노력이 필요합니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_술_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '저장과 보존에 유리합니다 — 저축이 잘 됩니다',
            '인색해지면 관계가 상합니다 — 균형이 필요합니다',
            '확실한 형태의 재물이 유리합니다',
            '지출을 최소화하고 비상금을 확보하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_술_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '고집이 세져 마찰이 생길 수 있습니다 — 한 발 물러서세요',
            '메마른 감정을 채우려면 먼저 따뜻하게 다가가야 합니다',
            '오래된 관계에 감사를 표현하세요',
            '완고한 태도를 부드럽게 풀어야 관계가 지속됩니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_술_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '정리와 마무리로 내공이 깊어지는 시기입니다',
            '고집을 인정하고 유연함을 기르는 것이 과제입니다',
            '메마른 밭에 물을 주듯, 자신을 돌보는 시간이 필요합니다',
            '묵은 것을 비우는 것이 새로운 성장의 시작입니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_술_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '메마름을 채우고 자신을 돌보세요',
            '정리와 마무리에 집중하세요',
            '완고함을 경계하고 유연해지세요',
          ],
          closing: '마른 밭에 물을 주는 사람이 다음 수확을 준비합니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 기_해: 겨울, 토극수(극) ──
    {
      month_pattern_id: '기_해', day_master: '기', month_branch: '해',
      season: '겨울',
      element_interaction: '극 (토극수) — 큰 물이 밭을 적셔 흔들림, 변화와 불안',
      label: '기토 × 해월 — 큰 물이 밭을 적시는 달, 변화 속에서 불안을 다스려야 한다',
      modules: [
        { module_id: '기_해_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '밭이 물에 적셔 흔들립니다 — 불안과 걱정이 큰 시기입니다',
            '물의 흐름을 막으려 하지 말고, 흐름에 대응하는 지혜가 필요합니다',
            '변화가 많은 시기입니다 — 중심을 잡고 차분하게 대응하세요',
            '밭은 산처럼 막을 수 없으니, 흐름을 읽고 대응하는 것이 관건입니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_해_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '차가운 물 기운이 몸을 식힙니다 — 따뜻하게 유지하세요',
            '신장, 방광, 비뇨기 건강에 주의하세요',
            '불안이 수면을 방해합니다 — 마음을 안정시키세요',
            '따뜻한 음식과 음료로 안에서부터 데우세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_해_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '변화와 이동이 많은 시기입니다 — 계획을 세우고 움직이세요',
            '불확실한 상황에서 차분함이 가장 큰 무기입니다',
            '재물의 기회가 눈앞에 있어도 신중하게 접근하세요',
            '한 번에 큰 것을 노리지 말고 단계적으로 접근하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_해_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '변화가 많고 감정이 흔들리는 시기입니다 — 중심을 잡으세요',
            '강렬한 인연이 다가올 수 있지만, 흔들리지 않게 조심하세요',
            '감정의 파도를 잘 다스려야 관계가 지속됩니다',
            '불안을 솔직하게 나누면 관계가 안정됩니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_해_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '재물의 흐름이 큽니다 — 욕심을 부리면 밭이 무너집니다',
            '보존이 우선입니다 — 위험한 투자, 큰 돈거래는 피하세요',
            '물처럼 흐르는 재물에 너무 매달리지 마세요',
            '확실하고 안정적인 형태로 재물을 묶어두세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_해_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '인연의 드나듬이 많은 시기입니다 — 가변적인 관계에 휩쓸리지 마세요',
            '불안이 관계를 긁습니다 — 차분함이 관계를 지킵니다',
            '확실한 사람을 구별하는 안목이 필요합니다',
            '변화 속에서 변하지 않는 관계를 소중히 하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_해_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '변화 속에서 중심을 잡는 연습이 가장 큰 성장입니다',
            '불안을 다스리는 것이 과제입니다',
            '물의 흐름을 읽고 대응하는 지혜를 기르세요',
            '변화를 두려워하지 말고 대비하는 것을 배우세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_해_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '불안과 걱정을 관리하세요',
            '중심을 잡고 차분하게 대응하세요',
            '재물의 욕심을 경계하세요',
          ],
          closing: '물의 흐름에 흔들리지 않고 대응하는 밭이 가장 비옥하게 남습니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 기_자: 겨울, 토극수(극) ──
    {
      month_pattern_id: '기_자', day_master: '기', month_branch: '자',
      season: '겨울',
      element_interaction: '극 (토극수) — 차갑고 깊은 물이 밭을 서서히 녹임, 감정과 침식',
      label: '기토 × 자월 — 차가운 물이 밭을 녹이는 달, 깊은 감정과 불안 속에서 안정을 되찾아야 한다',
      modules: [
        { module_id: '기_자_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '차가운 물이 밭을 서서히 녹입니다 — 불안이 깊은 시기입니다',
            '감정이 물처럼 깊게 고입니다 — 표현하고 풀어내세요',
            '안정감을 되찾는 것이 가장 중요합니다',
            '겉보기엔 잔잔해도 속은 깊게 흔들립니다 — 자신을 속이지 마세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_자_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '차가운 기운이 뼈까지 스며듭니다 — 몸을 따뜻하게',
            '신장, 방광, 혈액 순환에 주의하세요',
            '우울감이 올 수 있으니 — 햇빛을 자주 쬐고 사람을 만나세요',
            '따뜻한 음식과 음료로 안에서부터 데우세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_자_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '일의 흐름이 차분하지만 불안이 깔려 있습니다',
            '안정적인 기반이 중요합니다 — 흔들리지 않게 중심을 잡으세요',
            '겉으로는 평온해도 속으로는 변화가 진행 중입니다',
            '확실한 기반 위에서 움직이세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_자_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '감정이 깊고 차분하지만, 표현이 어려울 수 있습니다',
            '솔직하게 감정을 드러내세요 — 침묵은 오해를 키웁니다',
            '깊은 신뢰를 쌓는 시기이지만, 불안이 관계를 시험합니다',
            '감정이 고여 있으면 썩으니 — 흐르게 표현하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_자_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '재물의 흐름이 잔잔하지만 불안이 깔립니다',
            '안정적인 관리가 필수입니다 — 무리한 투자는 절대 피하세요',
            '작지만 확실한 수입원을 관리하세요',
            '불안이 판단을 흐리지 않도록 차분하게 관리하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_자_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '관계에서 소통이 줄어들 수 있습니다 — 의식적으로 연락하세요',
            '깊은 감정을 겉으로 드러내기 어려운 시기입니다 — 용기를 내세요',
            '혼자만의 시간도 필요하지만, 고립되지는 마세요',
            '차가운 시기일수록 따뜻한 연결이 생명줄입니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_자_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '내면의 뿌리를 깊이 내리는 시기입니다',
            '불안과 감정을 다스리는 것이 가장 큰 성장입니다',
            '차가운 시기의 인내가 봄의 싹을 키웁니다',
            '감정을 표현하는 용기를 기르세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_자_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '불안과 감정을 풀어내세요',
            '몸과 마음을 따뜻하게 유지하세요',
            '고립되지 않도록 사람과 연결되세요',
          ],
          closing: '깊은 물의 침식을 견디어 낸 밭이 가장 깊은 뿌리를 내립니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

    // ── 기_축: 겨울, 토(비견·겁재) ──
    {
      month_pattern_id: '기_축', day_master: '기', month_branch: '축',
      season: '겨울',
      element_interaction: '비견·겁재 (토 × 토) — 밭이 얼어붙어 정체됨, 인내와 잠복',
      label: '기토 × 축월 — 밭이 한겨울에 얼어붙는 달, 정체 속에서 자기를 돌보며 봄을 준비한다',
      modules: [
        { module_id: '기_축_mindset', domain_key: 'mindset', domain_label: '마음가짐', domain_index: 1,
          points: [
            '밭이 얼어붙어 정체됩니다 — 답답함과 걱정이 큰 시기입니다',
            '겉보기엔 멈춰 있지만, 속에서는 씨앗이 잠복하고 있습니다',
            '인내와 자기 돌봄이 필요한 시기입니다',
            '정체를 실패가 아니라 비축의 시간으로 받아들이세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_축_health', domain_key: 'health', domain_label: '건강', domain_index: 2,
          points: [
            '얼어붙은 밭이 위장 기능을 떨어뜨립니다 — 따뜻한 음식이 필수입니다',
            '관절, 혈액 순환 부족을 조심하세요',
            '우울감이 올 수 있으니 — 따뜻한 사람과 시간을 보내세요',
            '찬 음식, 생것은 피하고 따뜻하게 조리된 음식을 드세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_축_career', domain_key: 'career', domain_label: '일과 직업', domain_index: 3,
          points: [
            '진전이 더딘 시기입니다 — 인내가 필요합니다',
            '새로운 시작보다 기존 일을 충실히 하는 것이 유리합니다',
            '묵묵히 기다리는 시간이 나중에 보람으로 돌아옵니다',
            '지금 쌓는 기반이 봄의 도약이 됩니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_축_romance', domain_key: 'romance', domain_label: '애정운', domain_index: 4,
          points: [
            '관계가 차분하고 정적인 시기입니다 — 서두르지 마세요',
            '감정 표현이 줄어들 수 있습니다 — 의식적으로 따뜻하게',
            '깊은 신뢰를 쌓는 시기입니다 — 시간이 관계를 완성합니다',
            '얼어붙은 시기이니 작은 온기가 크게 느껴집니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_축_wealth', domain_key: 'wealth', domain_label: '재물', domain_index: 5,
          points: [
            '저장과 보존에 유리합니다 — 저축이 잘 됩니다',
            '지출을 최소화하고 비상금을 확보하세요',
            '얼어붙은 시기에는 움직이는 것보다 지키는 것이 유리합니다',
            '확실하고 안정적인 형태로 재물을 묶어두세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_축_relationships', domain_key: 'relationships', domain_label: '인간관계', domain_index: 6,
          points: [
            '관계가 차분해지고 왕래가 줄어듭니다',
            '가까운 사람과 따뜻한 시간을 보내세요',
            '묵묵히 곁에 있는 사람의 소중함을 깨닫는 시기입니다',
            '적지만 깊은 관계에 에너지를 집중하세요',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_축_growth', domain_key: 'growth', domain_label: '성장과 학습', domain_index: 7,
          points: [
            '겉으로의 성장이 더딘 시기입니다 — 내면의 뿌리가 깊어집니다',
            '인내와 자기 돌봄이 가장 큰 성장입니다',
            '얼어붙은 땅 아래에서 씨앗이 자라고 있습니다 — 봄을 준비하세요',
            '조용히 배우고 정리하는 시간이 내공을 쌓습니다',
          ],
          closing: null, tone: 'natural', review_status: 'approved' },
        { module_id: '기_축_must_do', domain_key: 'must_do', domain_label: '이 월지 출생의 핵심 과제', domain_index: 8,
          points: [
            '인내를 가지고 기반을 다지세요',
            '따뜻하게 유지하고 자신을 돌보세요',
            '봄을 위해 에너지를 비축하세요',
          ],
          closing: '한겨울의 인내와 자기 돌봄이 봄의 가장 튼튼한 싹을 틔웁니다.', tone: 'natural', review_status: 'approved' },
      ],
    },

  ],
};
